### ISSUE TITLE
Add documentation for new-major features

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#121]
We should add documentation for the following topics:
1. Working of Safety-controller
2. Working of Machine-deployment with regards to priorities of Machine.
    - the feature we implemented for autoscaler integration.
3. Notable features in README at root location.
   - Rolling update, rollback, pause, autoscaler integration, health-check.
4. Working of base controllers
   - Behavior of machine/set/deployment controllers in different scenarios.
   - Maybe the way autoscaler Q&A looks like: 
     https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md
5. Working of bootstrap-token mechanism with Gardener at the time of machine-creation. 
   - This may fit-in gardener repository rather.

This should help larger audience to understand the internals/working of mcm, also help us re-directing many of the queries here.

**Comment by vlerenc** [comment]
Excellent, thank you!

**Comment by dkistner** [comment]
I will cover the Gardener related parts (point five).

**Comment by hardikdr** [comment]
Thanks Dominic, that would be nice !! :)

**Comment by hardikdr** [comment]
Waking this thread up to prepare a good FAQ for MCM. I would try to gather generic questions that have been asked by stake-holders in recent times and open a PR soon after to add it doku. Proposing the following major categories:

Questions:

## Basic
1. What is MCM ?
2. In what cases machine is triggered for deletion?
3. How are the Pod Disruption Budgets maintained in the MCM?
4. How does Cluster-autoscaler with MCM?
5. What is safety-net?

## How to?
1. How to better control the roll-out process of the machine-deployment?
2. How to selectively scale-down the machine?


## Internals 
1. What is the high-level design of the MCM?
1. What are the default timeouts in the machine's lifecycle?
2. How does the drain of the machines work with stateful applications? 
3. How is the roll-out implemented  ? 

## Troubleshooting
1. My machine is stuck in deletion for 1 hr, why?
2. My machine is not joining the cluster, why?
3. How do I know what's going on in MCM?



## Developer
1. How should I test my code before submitting a PR?
2. I need to change the APIs, what are the recommended steps?
3. How can I update the dependencies of MCM?

## In the context of Gardener
1. How is my worker-pool spread across zones?

**Comment by hardikdr** [comment]
It would be great to see more questions/answers contributed here, we shall open a WIP PR[again] and have them added incrementally. :) 

cc @prashanth26 @amshuman-kr @AxiomSamarth @zuzzas @rewiko @ggaurav10 @guydaichs

**Comment by Ido-Itz** [comment]
I'll start the Q&A thread as suggested, based on a conversation I had with @hardikdr just now 😄 

**Q**
We are going to set an exact value for `machineDrainTimeout` that fits our use case, after which we no longer mind if the drain will ignore PDBs.
I was wondering which value I should set for `maxEvictRetries` so that it wouldn't collide with the other configuration.
  
**A**
Hardik explained that if you set one then you shouldn't set the other. This is because when you set `maxEvictRetries` it is translated into the amount of time that it would take to perform these retries, and then configures the aforementioned `machineDrainTimeout` parameter with that value.

Thanks again @hardikdr

**Comment by hardikdr** [comment]
Basically in summary:

1.  If you dont set the maxEvictRetries, and set only the maxDrainTimeout.
    - MCM auto calculates the maxEvictRetries based on the drainTimeout.
2.  If you dont set the drainTimeout, and only set the maxEvictRetries:
    - Default drainTimeout is considered , and the MER you provided for each pod.
3. If you set both MER and drainTimoeut:
    - Then both will be respected.
4. If you set none:
    - Defaults are respected.

Added it to the list of questions, thanks for the contribution :)
