### ISSUE TITLE
Machines are getting terminated by MCM

### ISSUE THREAD

**Issue by nikhilsap** [gardener/machine-controller-manager#126]
We deployed a shoot cluster via a yaml file in K8s Gardener.
Shoot Details : 

> Cloud Provider : AWS  
Worker Nodes : 1 
Size : m4.xlarge
K8s Version : 1.10.5

The shoot/worker node is getting terminated within 8-9 mins in the seed cluster.
We got the following message from error log.

> Execution of (*HybridBotanist).ReconcileMachines did not succeed... (Failed to deploy the generated machine deployments: 'Operation cannot be fulfilled on machinedeployments.machine.sapcloud.io \"shoot--userid--blr-aws-cpu-worker-x-z1\": the object has been modified; please apply your changes to the latest version and try again')" opid=c7OdYd3s shoot=userid/blr-aws
time="2018-07-24T16:25:51+05:30" level=error msg="Maximum waiting time exceeded after 30s waiting time, returning error

AWS Console : 

![image](https://user-images.githubusercontent.com/41104107/43180596-8e056032-8ff6-11e8-95ac-f306c819fae0.png)

We tried deleting the shoot and created again and encountered same issue.

**Comment by prashanth26** [comment]
I am guessing that this is the same issue observed with the older MCM version (0.7.0), which has been fixed once the new MCM was used?

**Comment by nikhilsap** [comment]
Yeah In the new version of MCM (0.8.0) , this issue has been fixed. 
So closing it.

**Comment by nikhilsap** [comment]
Again we are facing the same issue. Reopening .

**Comment by prashanth26** [comment]
Have tried using the latest version of MCM?
https://github.com/gardener/machine-controller-manager/releases/tag/0.9.0

**Comment by prashanth26** [comment]
This issue has been fixed in the latest release. Closing this issue. Kindly let us know, if you are seeing this issue again.
