### ISSUE TITLE
Investigate if control plane component restart, triggers recreation of healthy nodes

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#127]
Investigate if machine re-creation occurs when MCM/APIserver/ETCD restarts after a long time (more than health timeout). 

If this occurs, fix this by checking for machine health status on re-start before re-creating machines.

**Comment by bergerx** [comment]
This is related to https://github.com/gardener/gardener/pull/204

**Comment by prashanth26** [comment]
I have investigated this, and the current version of MCM first checks for current node health and if it is healthy doesn't try to re-create even if the machine status reflected unhealthy.

I have tried this by simulating the same. Hence closing this issue. Reopen if you see this again.
