### ISSUE TITLE
Unit tests for machine controller

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#129]
This issue is to track the progress of unit tests for machine controller.

**Comment by prashanth26** [comment]
Closing this issue as there are basic until tests in place today. Of course, we have to improve the coverage over time. Following the current principle of adding tests for each fix/enhancement.

**Comment by vlerenc** [comment]
@prashanth26 Do we in the meantime have tests that test e.g. whether volumes are deleted when the machines are terminated?

**Comment by prashanth26** [comment]
Hi Vedran,

No, we still don't have that. Sorry, I missed that. I have created an issue for the same here - https://github.com/gardener/machine-controller-manager/issues/498. Something that will be picked up in the coming days.
