### ISSUE TITLE
Improve control of MCM over cloud-config and system-level knobs

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#138]
We need to soon define a way, with which mcm can both configure kubelet and system-level knobs. Couple of use cases I can see are:

- Dynamically setup Node-Allocatables' via kubelet based on the type of Machine. 
- To improve the support for multiple Operating systems. For instance, SLES requires its own certain system-level settings before it can bootstrap kubelet properly.

This issue essentially boils down to the question: Which component takes responsibility of managing/maintaining the cloud-config in our case ? And what could be the strategy for in-place updates in future - SSH(?) or using downloader-script?

 - We could generate it, via Gardener with certain PLACE_HOLDERS, and let MCM replace those PLACE_HOLDERS optionally. OR
- We could generate the complete cloud-config at MCM, and maintain it there.
Open for thoughts-discussions.

**Comment by vasu1124** [comment]
refer to GKE's formula: https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#memory_cpu

**Comment by prashanth26** [comment]
Closing in favour of #185
