### ISSUE TITLE
Panic happens when only Alicloud Machine Class is created without a related secret

### ISSUE THREAD

**Issue by jia-jerry** [gardener/machine-controller-manager#145]
If an Alicloud Machine Class is created and no secret for Alicloud is created, machine controller manager will panic:

panic: not support yet [recovered]
	panic: not support yet

goroutine 387 [running]:
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x17eca20, 0x1deb8c0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/gardener/machine-controller-manager/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).Init(0xc42032c8c0, 0xc42032c8c0, 0xc420c78ce0)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:48 +0x39
github.com/gardener/machine-controller-manager/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs.NewClient(0xc420c78ce0, 0x1f, 0xc420c78ce0)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs/client.go:31 +0x40
github.com/gardener/machine-controller-manager/pkg/driver.(*AlicloudDriver).getEcsClient(0xc420c4d480, 0x1d, 0x1c6eaf7, 0x13)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/driver/driver_alicloud.go:315 +0x16a
github.com/gardener/machine-controller-manager/pkg/driver.(*AlicloudDriver).getVMDetails(0xc420c4d480, 0x0, 0x0, 0xc420bb7c00, 0xc4201c8ea0, 0x0, 0x0, 0xc420567330)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/driver/driver_alicloud.go:256 +0x1f0
github.com/gardener/machine-controller-manager/pkg/driver.(*AlicloudDriver).GetVMs(0xc420c4d480, 0x0, 0x0, 0xc42029c500, 0x14, 0x1bfc320)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/driver/driver_alicloud.go:283 +0x6b
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkMachineClass(0xc4200dcc80, 0x1bfc320, 0xc420b48600, 0xc420376280, 0xc420265a30, 0xd, 0xc42029c500, 0x14)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:351 +0x13a
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkAlicloudMachineClass(0xc4200dcc80)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:320 +0x125
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).checkVMObjects(0xc4200dcc80)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:158 +0x63
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).reconcileClusterMachineSafetyOrphanVMs(0xc4200dcc80, 0x0, 0x0, 0x0, 0x0)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety.go:52 +0xea
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).(github.com/gardener/machine-controller-manager/pkg/controller.reconcileClusterMachineSafetyOrphanVMs)-fm(0x0, 0x0, 0xc42000a200, 0x17eca20)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:458 +0x3e
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1.1(0x1e25ce0, 0xc42000a200, 0xc4202f6f00, 0x455301, 0xf, 0x1c7bcb2, 0x1d, 0xc4203ebb00)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:496 +0xe5
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1()
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:513 +0x8d
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420c4d400)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420c4d400, 0x3b9aca00, 0x0, 0x1ad3d01, 0x0)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420c4d400, 0x3b9aca00, 0x0)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/gardener/machine-controller-manager/pkg/controller.createWorker.func1(0x1e25ce0, 0xc42000a200, 0x1c7bcb2, 0x1d, 0xf, 0x1, 0xc4202f6f00, 0x0, 0xc420264090)
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:475 +0x91
created by github.com/gardener/machine-controller-manager/pkg/controller.createWorker
	/Users/i041966/projects/go-root/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:474 +0xbe

**Comment by prashanth26** [comment]
Hi @jia-jerry,
                      Is this issue resolved or still needs to be worked on?

Regards,
Prashanth

**Comment by jia-jerry** [comment]
Hi @prashanth26 ,

This issue  still exists. It is not a blocking issue. The root cause is an invalid client initialization:
```
github.com/gardener/machine-controller-manager/pkg/driver.(*AlicloudDriver).getEcsClient

github.com/gardener/machine-controller-manager/pkg/driver/driver_alicloud.go: 286
```
I will follow up this issue.

**Comment by prashanth26** [comment]
Okay. Thanks for the update.
