### ISSUE TITLE
Enhance freeze logic

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#155]
We need to enhance the freeze logic of safety-controller to include scenarios when infrastructure is unhealthy in general. 
- Currently, MCM tries to re-create the machine, if the machine fails to provide heart-beat since configurable timeout-period[10mins].
- We need to consider the possibility when infrastructure itself is largely unhealthy and due to which MCM sees lot many unhealthy machines in a cluster. At such times, MCM should rather freeze itself than try to manage VMs-which would only increase pressure on infra and would be of no help.

One of the enhancement could be to freeze the MCM when more than X%[~50] of the machines are unhealthy since certain timeout period.

**Comment by prashanth26** [comment]
## Problem
Machine controller manager keeps trying to reconcile nodes into its desired state even when the following conditions occur, 
- The cloud provider 
- Apiserver is down/unreachable 
- Some (%/#) of nodes fail to join a machineset for a long period of time

### Goals
We need a mechanism to freeze and unfreeze the controller itself (or the machine objects) to handle above scenarios. 

### Non-goals
- The freezing and unfreezing must be automated 
- It should ideally exponentially backoff (with upper capping)

Related: https://github.com/gardener/machine-controller-manager/issues/75
