### ISSUE TITLE
Enable support for taints, annotations and labels 

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#174]
## Problem
There is no mechanism to sync the taints, annotations, and labels between machine-object and corresponding node-objects. This causes issues when we wish to automate the propagation of such features.

## Solution
Allow propagation of taints, annotations, and labels to be specified on machine objects and propagate the same onto their node objects (or vice-versa ?).

## Related issues
- https://github.com/gardener/gardener/issues/250
- https://github.com/gardener/machine-controller-manager/issues/120

**Comment by amshuman-kr** [comment]
Do we really need this feature? Do we need to sync taints and labels on `machines`? Can we not make things work with taints and labels on the `nodes` directly?

**Comment by prashanth26** [comment]
After having a follow-up discussion, the following are our findings. 

1. How do you sync labels, annotations & taints between machines and nodes? A two-way (superset) sync is not possible as it would lead to race conditions between the node and the machine object. Hence it would only make sense to have it propagated from machines ----> nodes?
2. Do we sync these across the different controllers as well? Meaning labels, annotations & taints added on the machine-deployment propagates to ---> machine-set ----> machine ----> nodes?

**Comment by prashanth26** [comment]
The community has similar issues open here - https://github.com/kubernetes-sigs/cluster-api/issues/493, https://github.com/kubernetes-sigs/cluster-api/issues/458. Looking at the discussions from the community, there was a positive input by keeping them `the list of labels, taints, and annotations need to be additive (not authoritative)` refer - https://github.com/kubernetes-sigs/cluster-api/issues/493#issuecomment-420044515.

**Comment by prashanth26** [comment]
The discussion in the community is along the same lines that we internally had a discussion [here](https://github.com/gardener/machine-controller-manager/issues/174#issuecomment-427759127). It mainly revolves around the idea of propagation of labels. How do you sync labels between the different levels? 

nodes <---> machines <---> machineset <---> machinedeployment

From which direction do we propagate the labels? which to be considered as the source of truth?

For instance: If you add a label on the node object and if the machine object adopts this label. And now if the node label is deleted, should the label be deleted on the machine object or re-copied from the machine object to the node now? How do you define which is the source of truth? Both directions of propagation of labels look important at this moment.

**Comment by prashanth26** [comment]
Support for Gardener with labels, taints & annotations - https://github.com/gardener/gardener/pull/952. PR on hold waiting for MCM release with feature.
