### ISSUE TITLE
Bootstrap token generation to be handled at MCM

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#179]
## Issue

Currently bootstrap tokens for the machines are being created by the Gardener for a machineDeployment basis and are being passed into the cloud-config. However this is not ideal as all machines in a given period have the same bootstrap tokens and Gardener must be up to keep renewing these tokens.

## Possible Solution

- The Gardener would only pass a cloud-config with the bootstrap token secret name templated
- The MCM would create a new bootstrap token with every machine creation and deploy this token into the target cluster
- Now it replaces this secret token name in the cloud-config and deploys this machine
- Once the machine is created, it acquires the bootstrap token from the secret deployed and uses this to join the cluster
- The bootstrap token should be deleted either when the machine joins the cluster or the machine object is deleted
- This enhancement would require changes to both the Gardener and MCM

## Improvements

1. There is a one to one mapping between machines and bootstrap tokens hence eliminating security risks
1. Gardener no longer needs to be reconciled periodically to renew bootstrap tokens

## Related issues

1. [Custom OS Support](https://github.com/gardener/gardener/issues/262)
1. [Reconcile in Maintenance Time Window Only](https://github.com/gardener/gardener/issues/251)

**Comment by vlerenc** [comment]
:+1:

**Comment by prashanth26** [comment]
Closing in favor of - https://github.com/gardener/machine-controller-manager/pull/351.
