### ISSUE TITLE
Custom node label propagation

### ISSUE THREAD

**Issue by afritzler** [gardener/machine-controller-manager#182]
Are we currently propagating custom node labels when we autoscale or upgrade/recreate machines? It looks like they are lost when the machine is recreated. I know that this will be a hard thing to do, so I just wanted to open this issue as a reminder.

**Comment by prashanth26** [comment]
Hi @afritzler ,

I think you refer to something like [this](https://github.com/gardener/machine-controller-manager/issues/174)? If so, can i close this issue as this is a duplicate one?

**Comment by prashanth26** [comment]
Closing in favour of #174
