### ISSUE TITLE
Deletion of node object once VM is deleted

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#186]
## Issue
Currently, the KCM seems to be having a bug where sometimes it is not able to delete the node object when the VM is deleted. 

## Possible solutions
1. Trace back the issue with the community and fix it there on Kubernetes upstream
2. Force MCM for node object deletion once VM deletion returns successfully.

**Comment by jia-jerry** [comment]
It seems not easy for KCM to manage life cycle of node in out-of-tree cloud provider solution.  And also it not the duty for out-of-tree Cloud Controller Manager. 

So shall we choose solution 2?

**Comment by jia-jerry** [comment]
https://github.com/kubernetes/cloud-provider-gcp

**Comment by jia-jerry** [comment]
Cool. It is great. It seem Alicloud cloud provider lacks this node lifecycle management.

**Comment by rfranzke** [comment]
What's the progress here? @jia-jerry 
It's producing a lot of ops effort to manually delete these `Node` objects - every day.
Can you please give an update?

**Comment by jia-jerry** [comment]
> What's the progress here? @jia-jerry
> It's producing a lot of ops effort to manually delete these `Node` objects - every day.
> Can you please give an update?

I fixed this issue in CloudControllerManager for Alicloud. I repushed the image **jerryjxj/alicloud-controller-manager:1.9.8** for Gardener v0.19.0 

And also, for Gardener master branche, I changed registry server as **registry.eu-central-1.aliyuncs.com/gardener-de/alibaba-cloud-controller-manager:1.9.8**, which is the same as jerryjxj/alicloud-controller-manager:1.9.8.

I tried to pull the newest jerryjxj/alicloud-controller-manager:1.9.8 for each soild landscapes. Now every running landscape should be OK.

**Comment by rfranzke** [comment]
You force-pushed the same tag? Please don't do this in the future again, this is a) bad practice and b) won't work without manual interaction.

**Comment by jia-jerry** [comment]
Yes. 
Take your advice :)

**Comment by prashanth26** [comment]
So do we still need to explicitly delete the node object (at the MCM) on deletion of VM on the cloud provider from the MCM? - Option 2 above.

**Comment by jia-jerry** [comment]
For Alicloud, cloudprovider could handle it. There is special call-back in cloud provider API to tell the instance status. If it is correctly implemented, the node will be removed automatically. I think this is the desired feature of Cloud provider. 

There should be option 3. Cloud Provider handles it.
