### ISSUE TITLE
Enhance metrics endpoint

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#189]
## Issue
The metric endpoints currently only expose the machine objects managed by the machine controller manager. This could be more useful to track MCM freezing and # of API calls

## Solution
The metrics endpoint should expose more detailed metrics for MCM.
Like

- [x] # of machines, machineSet, machineDeployment
- [x] # of API calls to the cloud provider
- [x] Freeze status of MCM

**Comment by fsniper** [comment]
I was also working on this issue and may be the metrics from the below list can also be considered? I am ready to start on this and try to add some metrics if you have not already started working on this.

```
* crd:machinedeployment: count, age|created, availableReplicas, readyReplicas, replicas, updatedReplicas
* crd:machineset: count, availableReplicas, failedMachines, fullyLabeledReplicas, readyReplicas, replicas, age|created
* crd:machine: age|created, count, conditions, status
```

**Comment by prashanth26** [comment]
Hi @fsniper ,

We are happy to have you pitching in. You are more than welcome to take this issue up. The metrics you have mentioned above does make sense to me. In addition to that, if you are able to track the # of API calls to cloud provider (keeping a global atomic integer counter?) and also expose the [freeze status of the controller](https://github.com/gardener/machine-controller-manager/blob/master/pkg/options/types.go#L119) it would be great.

Thanks & Regards,
Prashanth

**Comment by fsniper** [comment]
- [x] # of machines, machineSet, machineDeployment
 - [x] machine info, created (age), conditions, phase
 - [ ] machineset info, created (age), status, created (age)
 - [ ] machinedeployment: info, created (age), status, conditions
 - [ ] # of API calls to the cloud provider
 - [ ] Freeze status of MCM

**Comment by prashanth26** [comment]
Reopening issue to have a second look at this, and see how they can be helpful while alerting.

**Comment by prashanth26** [comment]
Closing in favor of - https://app.zenhub.com/workspaces/5a5a7a3f1995e0507949552a/issues/gardener/machine-controller-manager/211
