### ISSUE TITLE
can't build with mcm dependency

### ISSUE THREAD

**Issue by shturec** [gardener/machine-controller-manager#196]
Currently, mcm is using quite outdated kubernetes dependencies (1.10.x). Gardener and projects depending on Gardener that are already on 1.12.+ need to manually remove `zz_generated.conversion.go`  in order to build correctly, because in the newer k8s versions `runtime.Scheme` API has changed disruptively and `scheme.AddGeneratedConversionFuncs` has been removed.

In fact, you probably only need your internal v1beta1 api package and should you chose to keep only it, `zz_generated.conversion.go` will not be necessary at all.

Please, either upgrade k8s dependencies to 1.12 and/or refactor your API for internal version only and remove `zz_generated.conversion.go`

**Comment by prashanth26** [comment]
Closing this in favour of - https://github.com/gardener/machine-controller-manager/pull/194. Please reopen if you see this issue again.
