### ISSUE TITLE
Machineset is recreated repeatedly if number of replicas in machinedeployment is set to 0

### ISSUE THREAD

**Issue by ggaurav10** [gardener/machine-controller-manager#197]
## Issue
Currently, MCM keeps creating and deleting machineset if the number of replicas in machinedeployment is set to 0.

Correct behaviour would be for MCM to stop acting on a machinedeployment if the number of replicas is set to 0.

**Comment by prashanth26** [comment]
There is a side effect of this issue where machine deployments are permanently frozen. We need to enhance this logic of unfreezing to even pick machine deployments that no longer have a machine set with the freeze labels.

**Comment by prashanth26** [comment]
This issue seems to be difficult to reproduce and doesn't seem to be causing any issues as of such. Hence parking this for the time being.

**Comment by AxiomSamarth** [comment]
/assign @AxiomSamarth 

I guess, it got assigned to @prashanth26 previously. Assigning it to me as per my discussions with Prashanth.

**Comment by AxiomSamarth** [comment]
The issue does not seem to be reproducible when tried with fresh deployments with 0 replicaset and even when scaled down to 0 replicaset.
