### ISSUE TITLE
Nodes went to NotReady state with burstable pods

### ISSUE THREAD

**Issue by KesavanKing** [gardener/machine-controller-manager#208]
I am doing some performance experiments with density framework. There, I  deploy pods  which doesn't have any resource limits. Initially the cluster has 5 nodes and max was set to 10. When I trigger the load,  pods increases and autoscale of nodes happened. Before the machines joined the cluster, all existing nodes also went to NotReady State

**Comment by ggaurav10** [comment]
Looks like this is because the pods grow up to use all available resources, and some of the system pods/processes might be under memory/cpu pressure.
Can you please provide the below section from the machine resources (in the control plane) that is NotReady
```
  status:
    conditions:
```
It can give details on below possible reasons:
KubeletHasSufficientDisk, KubeletHasSufficientMemory, KubeletHasNoDiskPressure, KubeletHasSufficientPID, KubeletReady

**Comment by KesavanKing** [comment]
worker-kyb7e-z1-768777f49-jfqdh is not healthy since 10m0s minutes. Changing status to failed. Node Conditions: [{Type:OutOfDisk Status:Unknown LastHeartbeatTime:2018-12-28 02:53:45 +0000 UTC LastTransitionTime:2018-12-28 02:54:32 +0000 UTC Reason:NodeStatusUnknown Message:Kubelet stopped posting node status.} {Type:MemoryPressure Status:Unknown LastHeartbeatTime:2018-12-28 02:53:45 +0000 UTC LastTransitionTime:2018-12-28 02:54:32 +0000 UTC Reason:NodeStatusUnknown Message:Kubelet stopped posting node status.} {Type:DiskPressure Status:Unknown LastHeartbeatTime:2018-12-28 02:53:45 +0000 UTC LastTransitionTime:2018-12-28 02:54:32 +0000 UTC Reason:NodeStatusUnknown Message:Kubelet stopped posting node status.} {Type:PIDPressure Status:False LastHeartbeatTime:2018-12-28 02:53:45 +0000 UTC LastTransitionTime:2018-12-28 02:51:07 +0000 UTC Reason:KubeletHasSufficientPID Message:kubelet has sufficient PID available} {Type:Ready Status:Unknown LastHeartbeatTime:2018-12-28 02:53:45 +0000 UTC LastTransitionTime:2018-12-28 02:54:32 +0000 UTC Reason:NodeStatusUnknown Message:Kubelet stopped posting node status.}]

**Comment by KesavanKing** [comment]
`W1228 03:59:30.023764       1 machine.go:482] Drain failed for machine shoot--perf-load--density-worker-kyb7e-z1-768777f49-cmz5c - 
Buf: 
ErrBuf:WARNING: Ignoring DaemonSet-managed pods: calico-node-b65sd, kube-proxy-gg82s, node-exporter-pf529
WARNING: Ignoring DaemonSet-managed pods: calico-node-b65sd, kube-proxy-gg82s, node-exporter-pf529
There are pending pods when an error occurred: Drain did not complete within 5m0s`

**Comment by ggaurav10** [comment]
The kubelet stopped posting status. We will look into this.
The drain failure could be a symptom of previous issue. As the node/kubelet is NotReady, drain of pods failed.

**Comment by ggaurav10** [comment]
Observations:

The eviction thresholds are met. This is because the memory limit is not set on the pods, which keep growing in size. Even though attempt to recover memory is started, the node was restarted for some reason.

Below is snippet from events of a node:

```
Events:
  Type     Reason                     Age                 From                                                     Message
  ----     ------                     ----                ----                                                     -------
  Normal   Starting                   38m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Starting kubelet.
  Normal   NodeHasSufficientDisk      38m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientDisk
  Normal   NodeHasNoDiskPressure      38m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID       38m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced    38m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Updated Node Allocatable limit across pods
  Normal   NodeReady                  38m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeReady
  Normal   Starting                   38m                 kube-proxy, ip-10-250-28-124.eu-west-1.compute.internal  Starting kube-proxy.
  Normal   NodeHasSufficientMemory    23m (x2 over 38m)   kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientMemory

  Warning  EvictionThresholdMet       20m (x12 over 37m)  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Attempting to reclaim memory
  Normal   NodeHasInsufficientMemory  20m (x2 over 36m)   kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasInsufficientMemory
  Normal   NodeNotReady               14m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeNotReady
  Normal   Starting                   11m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Starting kubelet.
  Normal   NodeHasSufficientDisk      11m (x2 over 11m)   kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientDisk
  Normal   NodeHasSufficientMemory    11m (x2 over 11m)   kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure      11m (x2 over 11m)   kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID       11m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Warning  Rebooted                   11m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal has been rebooted, boot id: 33db80e3-8c4d-44a9-a1a9-247d2f48225f

  Normal   NodeNotReady               11m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeNotReady
  Normal   NodeAllocatableEnforced    11m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Updated Node Allocatable limit across pods
  Normal   NodeReady                  11m                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeReady
  Normal   Starting                   11m                 kube-proxy, ip-10-250-28-124.eu-west-1.compute.internal  Starting kube-proxy.
  Warning  EvictionThresholdMet       9m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Attempting to reclaim memory
  Normal   NodeHasInsufficientMemory  9m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasInsufficientMemory
  Normal   Starting                   5m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Starting kubelet.
  Normal   NodeAllocatableEnforced    5m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Updated Node Allocatable limit across pods
  Normal   Starting                   5m                  kube-proxy, ip-10-250-28-124.eu-west-1.compute.internal  Starting kube-proxy.
  Normal   NodeHasSufficientDisk      5m (x2 over 5m)     kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientDisk
  Normal   NodeHasSufficientMemory    5m (x2 over 5m)     kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure      5m (x2 over 5m)     kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID       5m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Warning  Rebooted                   5m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal has been rebooted, boot id: 3eb960e1-961c-4e09-a753-52ab650347e2
  Normal   NodeReady                  5m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeReady
  Warning  EvictionThresholdMet       4m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Attempting to reclaim memory
  Normal   NodeHasInsufficientMemory  3m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasInsufficientMemory
  Normal   NodeNotReady               2m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeNotReady
  Normal   Starting                   1m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Starting kubelet.
  Normal   NodeHasSufficientPID       1m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeHasSufficientMemory    1m (x2 over 1m)     kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure      1m (x2 over 1m)     kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientDisk      1m (x2 over 1m)     kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasSufficientDisk
  Normal   NodeNotReady               1m                  kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeNotReady
  Normal   NodeAllocatableEnforced    57s                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Updated Node Allocatable limit across pods
  Normal   NodeHasInsufficientMemory  57s                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeHasInsufficientMemory
  Normal   NodeReady                  57s                 kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Node ip-10-250-28-124.eu-west-1.compute.internal status is now: NodeReady
  Warning  EvictionThresholdMet       44s (x2 over 57s)   kubelet, ip-10-250-28-124.eu-west-1.compute.internal     Attempting to reclaim memory
```

**Comment by ggaurav10** [comment]
The node is rebooted by the kubelet health monitor:
Code snippet:
```
if [[ $count_kubelet_alternating_between_ready_and_not_ready_within_timeframe -ge $toggle_threshold ]]; then
   sudo reboot
```
**Next step:**
Find out why the node switches from ready to NotReady state even though kubeReserved is set to 80m CPU and 1GB memory.
Are above values not enough, or the memory reclaim process under event `EvictionThresholdMet` very slow (https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#kubelet-may-not-observe-memory-pressure-right-away)

Taking hints from http://node-perf-dash.k8s.io/#/builds
We can see that the for a decent 90 percentile API responsiveness, the kubelet CPU requirement is around 0.25, whereas we are reserving only 0.08.

As next step, we will run the test with higher kubeReserved value for CPU.

**Comment by ggaurav10** [comment]
Tried several steps:
1. Increased kubelet's `--kube-reserved` memory and CPU
1. Added kubelet's `--system-reserved` memory and CPU
1. Increased eviction thresholds (25% of 8GB total memory) so that the attempt to reclaim memory starts early

None of the above steps helped (even when used together). Looks like this is because when the memory usage of worker pods has a sudden surge, eviction is not fast enough.

Tried the same test in GKE cluster, and observed the same behaviour, except the reboot of the nodes. This is anyway because of our health-monitor script, which reboots the node if its state fluctuates.

The documentation (https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#kubelet-may-not-observe-memory-pressure-right-away) suggests 75% as eviction threshold (if acceptable).
I tried, and saw that the nodes stayed stable, however, in my opinion, this value is too high to be used for clusters.

I suggest we keep things the way they are, and document the mis-behaviour when pod requests/limits are not set properly.
WDYT @amshuman-kr @vlerenc

**Comment by ggaurav10** [comment]
Update: I tried 75% eviction threshold experiment again, and saw the node reboot this time.

**Comment by vlerenc** [comment]
Thanks. I guess, I agree. It is a fuzzy behaviour, so it can't meet all scenarios. Remains the question, whether this Web IDE test is "too" synthetic/not realistic or whether they really behave, such a load/spike can happen. If so, they need to do what you have suggested.

**Comment by KesavanKing** [comment]
Density Framework saturates the cluster with many pods based on the number of nodes and measure pod startup latency, scheduling time and other e2e metrics. We modified the framework to generate real workloads, pods consuming CPU & memory. We are trying to find all possible failover scenarios for the output qualification and meeting the standards.

**Comment by ggaurav10** [comment]
As discussed over call, closing this issue. If we see some real life workload showing same issues, we can revisit.
