### ISSUE TITLE
Documentation issue on page "https://github.com/gardener/machine-controller-manager.git"

### ISSUE THREAD

**Issue by freegroup** [gardener/machine-controller-manager#219]
we already have an AliCloud integration. I think this is part of the MCM - or?
but the readme.md from the repository doesn't mention this - too bad.

The page is visible on https://gardener.cloud/components/mcm/ as well.

---
Page: [https://github.com/gardener/machine-controller-manager.git](https://github.com/gardener/machine-controller-manager.git)
don't remove the link to the page. It's required for the processor

**Comment by freegroup** [comment]
<img width="997" alt="bildschirmfoto 2019-02-06 um 15 01 47" src="https://user-images.githubusercontent.com/1155039/52346600-35b6c000-2a20-11e9-8a2a-673ea3768b07.png">

**Comment by prashanth26** [comment]
Thanks for pointing this out. Shall fix this.

**Comment by hardikdr** [comment]
Thanks for reporting, I just fixed it.
