### ISSUE TITLE
Fake tests for CRDs to be handled better

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#240]
## Issue

1. Subresource fake tests handling shouldn't seem to work as expected for all cases. For instance, CRD updateStatus() updates the entire object instead of the status. Refer - https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L101-L103
2. Patch on CRDs doesn't seem to work properly with CRDs? Need to check again

## Solution

Need to fix this upstream and port these changes here.

**Comment by himanshu-kun** [comment]
/close as the relevance can't be judged from the given issue description.
Also this should get solved with controller runtime refactoring.
