### ISSUE TITLE
Mitigate Azure VM Deletion Race Condition

### ISSUE THREAD

**Issue by vlerenc** [gardener/machine-controller-manager#255]
As was identified, kube-controller-manager implementation for Azure interferes with MCM VM deletion and due to an infrastructure race condition may leave VMs in inconsistent state, breaking all automation. The infrastructure team is committed to fix the race condition, but we planned in the meanwhile to implement a mitigation (evict, then delete the pods, then detach all disks, then delete the VM).

**Comment by prashanth26** [comment]
Hi @vlerenc ,

From an MCM perspective, this issue has been resolved by this PR - https://github.com/gardener/machine-controller-manager/pull/248. You can take a look at the release notes to confirm expected behavior.

**Comment by vlerenc** [comment]
Thank you very much @prashanth26. :-)

**Comment by prashanth26** [comment]
Closing this issue WRT #248
