### ISSUE TITLE
MCM respects taints with only unique keys

### ISSUE THREAD

**Issue by PadmaB** [gardener/machine-controller-manager#267]
In case of multiple taints with same key but different values [with different effects as appropriate], MCM applies only one taint and ignores the rest.
However, kubernetes allows multiple taints with same key as long as values and effects are valid and meeting the necessary conditions.
MCM should respect the behavior of kubernetes and override any of those

**Comment by prashanth26** [comment]
Solution:

We plan to use a 3-way merge to mitigate this. Thereby also allowing users to delete ALTs.
