### ISSUE TITLE
Integrate Node Problem Detector

### ISSUE THREAD

**Issue by vlerenc** [gardener/machine-controller-manager#28]
# Story
- As provider I want to reuse the work the community did around the Node Problem Detector (NPD), so that I can further improve the quality of our Gardener offering.

# Motivation
The plan by @hardikdr and @prashanth26 (see gardener/gardener#19) was to start integrating the NPD when they have capacity to also join the community in developing a/the remedy controller, maybe supported by the work done in the machine controller manager.

# Acceptance Criteria
- [ ] NPD is deployed on the machines
- [ ] Remedy steps integrate well with the machine controller manager

# Resources
See also https://www.youtube.com/watch?v=4QiWLxG-SlY&feature=youtu.be (minute 16-18).

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by prashanth26** [comment]
NPD is an independent component to be deployed along with the MCM. However, the MCM exposes flag/configurations where machines can be replaced based on `node-conditions` set by the NPD. Refer - https://github.com/gardener/machine-controller-manager/pull/478/files#diff-fe88a08ccd7c50ae45f70c808813c2d5R34. 

/close
