### ISSUE TITLE
Forceful deletion of Machine

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#281]
## Problem
We recently removed the support for forceful deletion of the machines in the cluster. Forceful deletion allowed to skip the drain while deleting the kubernetes-nodes. 

We need to investigate the behavior of MCM while deleting the Shoot-cluster especially when target-APIServer is not reachable. 
- I believe MCM keeps failing/attempting to drain the node, in turn blocking the deletion of the machine even while shoot-deletion. 

## Solution
The probable solution could be to re-check the reasoning behind disabling the forceful deletion and enable it again if possible.

**Comment by prashanth26** [comment]
One reason why we had restored to always calling a drain before deletion of node was to make sure there was no race condition between MCM and Kubernetes in attaching/detaching PVCs attached to a node being deleted.

But to address the problem of drains failing for cluster's whose APIServer is not reachable, would it be safe to ignore calling drain for cluster's whose APIServer is not reachable? Not sure, just think out loud here.
