### ISSUE TITLE
Improvements for MCM

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#287]
## Issue

There are several optimizations identified for MCM to make it run better. 

## Solution

- [ ] Eliminate all infinite for loops
- [ ] Tag/mark machines while creation to identify each of them uniquely 
- [ ] Get rid of any GET calls before making UPDATES
- [x] Don't process on updated objects
- [ ] Safety controller to be re-written with an event-based mechanism
- [ ] Use pointers to struct. There is far too much implicit struct copying going on especially in range for loops.

Credits: @mvladev

**Comment by amshuman-kr** [comment]
- [ ] Use pointers to struct. There is far too much implicit struct copying going on especially in range for loops.

**Comment by prashanth26** [comment]
Things are getting better with https://github.com/gardener/machine-controller-manager/pull/460. However, will keep this issue open to tracking exact improvements.

**Comment by himanshu-kun** [comment]
/close
#724 An umbrella issue for tracking all MCM refactoring.
