### ISSUE TITLE
Orphan NICs issue

### ISSUE THREAD

**Issue by MSSedusch** [gardener/machine-controller-manager#298]
When MCM cannot create a VM on Azure e.g. because the user does not have quota for the VM type, MCM creates a lot of orphaned NICs.

You can reproduce it if you do not have quota for M series VM but create a cluster with M series VMs in a worker pool

**Comment by prashanth26** [comment]
Thanks for reporting this issue @MSSedusch. We shall certainly try to reproduce this and fix it.

**Comment by prashanth26** [comment]
From what I can see, on the failure of creation of VMs we do not delete the last created NIC which is leading to this behavior - https://github.com/gardener/machine-controller-manager/blob/master/pkg/driver/driver_azure.go#L345-L355
