### ISSUE TITLE
Improve logs while draining of machines

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/machine-controller-manager#305]
### Issue

The current logs related to the drain logic mostly mention only the names of the pods being acted upon. This makes live tracking/monitoring/debugging hard to identify which machine/node is affected.

### Solution

Include the machine/node name in the logs related to the drain logic in addition to the names of the affected pods.

**Comment by prashanth26** [comment]
Need to still log the deletion/eviction/detachment times for Pods/PVs.

**Comment by prashanth26** [comment]
Closing in favor of - https://github.com/gardener/machine-controller-manager/pull/315
