### ISSUE TITLE
Machine deletion fails when shoot is not reachable

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#308]
## Issue 

Machine deletion fails when the shoot is not reachable (VPN was down on shoot cluster in gardener). Need to check why this was happening.

**Comment by ggaurav10** [comment]
Could the underlying issue be same as in https://github.com/gardener/machine-controller-manager/issues/306?
The drain might have been failing, and drain timeout of 12 hours wasn't hit...

**Comment by prashanth26** [comment]
No, in this case the drains were calling for force deletion but still kept failing. I could see that the shoot's VPN was down and the node update was just getting stuck. But I didn't understand why it was just stuck and couldn't return the right error that the node wasn't reachable. And even it looked like node GET calls were not returning error. 

When shoot VPN was down, this passed -  https://github.com/gardener/machine-controller-manager/blob/master//pkg/controller/drain.go#L889, but this timedout - https://github.com/gardener/machine-controller-manager/blob/master//pkg/controller/drain.go#L901.
