### ISSUE TITLE
Additional (+ encrypted) ephemeral worker/node disks

### ISSUE THREAD

**Issue by rfranzke** [gardener/machine-controller-manager#338]
We should investigate what is necessary to enable MCM to create machines with more than one disk. Optimally, it would support an arbitrary amount of additional disks per created machine.
Also, MCM should be made capable of encrypting these disks in case it is supported by the backing infrastructure provider (e.g., AliCloud supports encrypted disks).

**Comment by yarivlifchuk** [comment]
Application Studio (Web IDE DevX) uses ephemeral disk in AliCloud,AWS,Azure,NS2
Encrypted Ephemeral storage (not storage class) requires allocate additional Disk for each node and make it encrypted. in AliCloud there is only a System Disk and not a Data Disk.System Disk is not encrypted (for OS use).
The requirement for encrypted data disk is coming from SAP IT Global Security 
https://wiki.wdf.sap.corp/wiki/display/itsec/Alibaba+Cloud+Security+Procedure

Impact: Operator IaaS can take the disk and expose the customer data. WebIDE is going GA on Ali  on Sep 2019

**Comment by prashanth26** [comment]
- [ ]

**Comment by prashanth26** [comment]
Additional disks (+encryption in some cases), are implemented with 

AWS - https://github.com/gardener/machine-controller-manager/pull/378
Alicloud - https://github.com/gardener/machine-controller-manager/pull/397
Azure - https://github.com/gardener/machine-controller-manager/pull/397
GCP - https://github.com/gardener/machine-controller-manager/pull/414

**Comment by hardikdr** [comment]
This can be closed in favor of: https://github.com/gardener/machine-controller-manager/issues/462
