### ISSUE TITLE
Remove public IP's from gcp worker

### ISSUE THREAD

**Issue by schrodit** [gardener/machine-controller-manager#339]
Currently only gcp vm's get a public IP which is then restricted with a firewall rule that denies all traffic to this nodes except ports 443 and 80.

With the new kubernetes version 1.16.0 an new conformance test was introduced that tests if a service with a `NodePort` can be reached with its internal and external IP (only when a external IP is available). 
This tests fails on gcp as only 443 and 80 port is allowed and therefore Gardener is not currently not k8s conformant.

To unify the setup across all cloudproviders and make Gardener Clusters K8s conformant we have to remove the public IP form gcp workers.

cc @DockToFuture

**Comment by prashanth26** [comment]
Have made the changes here - https://github.com/gardener/machine-controller-manager/pull/340

**Comment by vlerenc** [comment]
We had a discussion with @zanetworker and he will discuss also with @DockToFuture and come up with a plan how to introduce that for our GCP-based clusters. Most likely only from 1.16 onwards (to pass the conformance tests again). We would have to inform our stakeholders, though, if we would change the behaviour (people might have made themselves already dependent on that implementation detail). That topic is not new, but considering this new conformance check, it could some undesired priority, unfortunately.

**Comment by prashanth26** [comment]
Alright @vlerenc . We shall keep some buffer for that. 

@zanetworker - Please keep us posted on your discussions here. TIA.

**Comment by zanetworker** [comment]
@prashanth26 Sure.

**Comment by zanetworker** [comment]
So as per our discussion, the following steps will be taken: 
- [ ]  Cloud NAT approach will be tested manually to make sure its working. 
- [ ]  Cloud NAT will be created for every region, and only new shoot subnets will be attached to it (while keeping their public IP, since the public IP takes precedence, no downtime should be noticed) 
- [ ] Merge change to disable public IPs by default from the MCM, namely (https://github.com/gardener/machine-controller-manager/pull/340)

**Comment by schrodit** [comment]
@hardikdr can we reopen this issue https://github.com/gardener/gardener-extensions/issues/411 until is fixed?

**Comment by rfranzke** [comment]
Why? This issue is fixed, from MCM side it's implemented correctly.

**Comment by schrodit** [comment]
The mcm part of the issue is fixed. But not the issue itself. We are still unable to execute the conformance tests and therefore unable to pass our release testing.
We just wanted to keep it open for release decision/documentation purposes until it is completely fixed.

Alternatively, we could transfer the issue or create a new one in the extensions?

**Comment by rfranzke** [comment]
We already have two now:

* https://github.com/gardener/gardener-extensions/issues/408
* https://github.com/gardener/gardener-extensions/issues/411

I don't think we need a third one.

**Comment by schrodit** [comment]
ok didn't know about the second issue. We then use https://github.com/gardener/gardener-extensions/issues/408 for reference 👍
