### ISSUE TITLE
Cross-check the existence of machine before creating the new one.

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#349]
## Issue
Currently, we create a new machine every time a fresh/un-processed machine-object is seen. This can lead to the state of creating an extra machine if the controller restarts while the machine is being provisioned.
- For now, the Safety controller comes to rescue and deletes such extra machines if created in rare-situations, but it would be nice to avoid it altogether.

## Solution
We should incorporate a minor improvement of first checking if machine already exists on infra, and make a request to create a new machine only if it does not. This can be achieved by tagging the virtual-machines on infra appropriately by machine-names.

cc @prashanth26

**Comment by prashanth26** [comment]
Shall be fixing this issue with the #178 changes.

**Comment by prashanth26** [comment]
All OOT controller follow this principle. And all providers will be eventually moved OOT. Hence closing this here.
