### ISSUE TITLE
Remove dependency on MachineClass while deleting MachineDeployment

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#357]
## Issue
Currently, we block the deletion of the MachineDeployment if referred MachineClass is missing. I guess it makes sense to avoid/block enqueueing the MachineDeployment while creation if referred MachiineClass is missing, which we already do. But for any reason, if referred MachineClass is deleted, and it can be ensured that no Machines are lying around referring to it, probably it should be safe to delete such a MachineDeployment.

## Probable Solution
Allow deletion of MachineDeployment, if `Spec.Replicas=0`, no child objects [machine-objects, in case the controller crashed immediately after] exists. Open for suggestions.

/cc @prashanth26

**Comment by prashanth26** [comment]
I was wondering if we can get rid of the machineClass check logic in `machineDeployment` and `machineSet` reconcilation? Refer - https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/deployment.go#L467-L471.

**Comment by amshuman-kr** [comment]
Not sure if we can completely get rid of it. But certainly can do for the deletion scenario, I think.

**Comment by hardikdr** [comment]
There is also a perspective that, we might want to keep the footprint of VMs created in the cloud in case the MachineClases are "mistakenly" deleted, which can be done by keeping the Machinedeployment, not sure this might be too defensive as well...
- if we can ensure, the related machine-objects are also gone then probably it would be safer to delete the MachineDeployment.
