### ISSUE TITLE
Node objects with mismatching provider IDs

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#361]
## Issue

It was observed that the `node.Spec.ProviderID` was inconsistent from the instanceID on openstack and `machine.Spec.ProviderID`.  Need to find out why this happens.

Two parts to this issue

- [ ] Fix the providerID inconsistency.
- [ ] Align `node.Spec.ProviderID` and `machine.Spec.ProviderID` format.

**Comment by TheBigElmo** [comment]
During the provisioning of the shoot, we observed that more than the defined amount of workers were provisioned on OpenStack. Instead of 4 workers, it tried to provision 7. After some time the 3 additional ones were gone. Maybe this has something to do with this issue.
