### ISSUE TITLE
Reduce drain-timeout

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#372]
## Issue
Currently, our default drain-timeout for all shoot-machines is 2 hours and we also force-delete the machines if the previous drain has failed. With recent investigation, we realized, it might not be best to skip drain altogether if previous drain for a machine has failed, it could potentially violate the PDBs. We are now reverting to not skip the drain in such cases.
- This brings a situation where a failed drain will be tried constantly till a drain-timeout of 2 hours. A drain could fail for a healthy machine for many natural reasons when we should only retry. But then it will be stuck in draining for 2 hours- which could be undesirable.

## Probable Solution
- Avoid skipping the drain when the previous drain has failed.
- Reduce the default drain-timeout for all shoots to ~20 minutes. Allow configuring the drain-timeout via shoot-spec. Consumers looking towards larger drain-timeouts should better configure it via shoot-spec than we set large values for all clusters.

**Comment by amshuman-kr** [comment]
👍 Can we add to the scope exposing the drain timeout issues in the `Machine`/`MachineSet`/`MachineDeployment` status?

**Comment by prashanth26** [comment]
CC: @vlerenc

**Comment by vlerenc** [comment]
I would need more information to think about it. From the outside though, a general drain timeout seems difficult. It will depend on the number of pods scheduled, especially those with volumes. It may vary from end user to end user and even the end user may see variance and might be unable to come up with a golden number. In the beginning we discussed some adaptive drain time, I believe, dependent on the number of pods (with volumes) scheduled to that machine.

I also would need to understand better what can go wrong. Infrastructure problems blocking operations? Do we know of some of these conditions and can we put that knowledge to our and the end users advantage?
