### ISSUE TITLE
Machine deletion fails to evict Daemonset pods for k8s 1.16.2

### ISSUE THREAD

**Issue by ashwani2k** [gardener/machine-controller-manager#383]
**Problem**:
While implementing out-of-tree driver for GCP, the deletion flow errors out with the following message 
`the server could not find the requested resource: calico-node-vsj6s, kube-proxy-6shpg, node-exporter-gfnxd, node-problem-detector-fch96`. 

**Symptom**:
on further analysis I see that the API group of Dameonset has now been promoted to apps from extensions.v1beta1 and that might be a reason why the resource is not found by the machine-controller-manager. 

Can you please verify the symptom and resolve the issue.

**Comment by prashanth26** [comment]
I think updating the k8s vendor versions to the latest should fix this issue. Need to double-check this though.
