### ISSUE TITLE
Make MCM `zone` aware.

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#392]
## Improvement
Currently, MCM depends on the `Region` field of MachineClass while spawning machines in specific regions/zone. We should probably somehow introduce the `zone` information and ensure machines are created in the specific zone of the region. There might be changes in how providers support this, but we should add wherever possible.
- The `Scale-to-zero` feature of autoscaler has a direct dependency on this feature, in terms of node-affinity against zones.
Refer:  [#36](https://github.com/gardener/autoscaler/pull/26#discussion_r366295998) in autoscaler.

Also a related issue on gardener: [#1673](https://github.com/gardener/gardener/issues/1673#issuecomment-562624529)

cc @rewiko

**Comment by prashanth26** [comment]
@hardikdr - do we still need this issue or is it resolved?

**Comment by hardikdr** [comment]
Idea is to have a zone information in the MachineClass for each provider, as this is needed for autoscaler to scale from zero.
This was implemented for AWS, but not for all.
I suggest, we keep it open, and later move this issue to each provider-specific machine-controller, to be tackled separately.

**Comment by prashanth26** [comment]
Related to https://github.com/gardener/autoscaler/issues/27.
