### ISSUE TITLE
Probable Azure improvements for MCM.

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#393]
# Issue
We recently faced an issue with the azure provider, where all of the VM-operations in the given Availibility-set was stuck due to the specific disk-detachment issue in one of the VMs.

## What was observed?
- A data-disk was deleted successfully. The same deleted disk was found attached to the other VM. This situation brings the entire AV-set into the inconsistent state, eventually leading to the failure of all the other operations in the same AV-set.

## RCA from Azure:
```
From the backend logs I can see the following scenario that caused the issue and the VM in a failed state after deleting the disk :
 
at 2020-01-10 16:13:50.682, see disk successfully detached
at 2020-01-10 18:21:59.167, disk is successfully deleted
 
at 2020-01-10 18:24:53.160, see attach disk operation for the disk: shoot-garden-abc-dynamic-pvc-abcd-1234-1234
but it failed as the disk cannot be found (expected as already deleted)
this is the operation to put VM in failed state
Why the script you are using is trying to reattach the disk after it was deleted? I can see request number 3 coming from the application : mapping to xyz-account
```

## Quick workaround:
This issue was resolved by recreating the deleted-but-attached disk with the same name and size. The newly created disk re-attached itself to the VM, which eventually led to the success of other stuck operations in AV-set.

# Solution
Based on the RCA from Azure, we need to investigate further the azure-operations we do with disks/VMs. This could also be potentially related to the CCM/KCM issue, as MCM never tries to attach the disk back to the VM.

**Comment by hardikdr** [comment]
cc @ialidzhikov @prashanth26 @vpnachev @amshuman-kr

**Comment by MSSedusch** [comment]
One of our support engineers suggested to update the CRP (Compute Resource Provider) API version to a more recent version to avoid issues with failed Availability Sets. Can you please update the RP versions to

	"github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute"
	"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-11-01/network"
	"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources"

https://github.com/gardener/machine-controller-manager/blob/master/pkg/driver/driver_azure.go#L33-L35

**Comment by prashanth26** [comment]
We identified MCM restarts during machine creation/deletion (on azure) could lead to orphan VMs.
1. Make a list call to verify any remaining infra before deletion
2. Use identifier/tags to identify the same

**Comment by dkistner** [comment]
@prashanth26  I can do that and incorporate it in my pr to upgrade the azure sdk, which I'm still testing.

**Comment by prashanth26** [comment]
@dkistner - If it's possible that would be great. Even if not it's alright. Otherwise, I can raise a parallel PR.

**Comment by dkistner** [comment]
Yep will do.
/assign

**Comment by prashanth26** [comment]
@dkistner - I have opened up an seperate issue to fix the orphan resources topic here - https://github.com/gardener/machine-controller-manager/issues/423.  If you haven't started working on you may ignore implementing it here - https://github.com/gardener/machine-controller-manager/issues/393#issuecomment-591945623. I shall address the same on #423

**Comment by dkistner** [comment]
I have updated the pr #406 and list now for dependant resources after an Azure machine has been deleted.
