### ISSUE TITLE
Optionally allocate from and release machines to a shared machine pool

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/machine-controller-manager#417]
### Kind

Feature request.

### Context

The time for a new machine to be created and join the Kubernetes cluster is relatively long (upto 10m in some cloud providers). When the `machine-controller-manager` is used with the [`cluster-autoscaler`](https://github.com/gardener/autoscaler), this causes a the pod scheduling latency to spike whenever the cluster has to be scaled up.

There are three options here.

1. Accept the latency if it is tolerable for the use-case.
1. Don't use the `cluster-autoscaler` if the cost is tolerable.
1. Use low-priority pods to [reserve excess capacity](https://github.com/gardener/gardener/tree/master/charts/seed-bootstrap/templates/reserve-excess-capacity) in the cluster. This has cost implications but less than option 2.

### The Problem

Even though option 3 has less cost implication than option 2, reserving excess capacity per cluster is wasteful in terms of resource utilisation and ultimately in terms of cost. This manifests even more clearly in the case where are multiple gardener shoot clusters created using the same infrastructure credentials (such as the gardener seed clusters in a decently large gardener landscape).

### Improvement

_It might be nice if the reserve excess capacity can be shared across multiple clusters that share the same infrastructure credentials._

#### Benefits
- The overall reserve excess capacity (across the cluster that share it) can be reduced while still mitigating the scheduling latency spikes during cluster scale up.
- This could especially help reduce the cost in gardener seeds that share the the same infrastructure credentials.
- The [reserve excess capacity per gardener seed clusters](https://github.com/gardener/gardener/tree/master/charts/seed-bootstrap/templates/reserve-excess-capacity) can be removed.

### Proposed Solution

1. Introduce an optional pool of VMs (already created) that are expected to be maintained using the same credentials as what the `MachineDeployments` use. Such a pool could have its own min and max size (number of VMs) configuration.
   1. Automatically manage the VMs in the pool
       1. If the pool grows beyond the configured max size, actually delete VMs from the infrastructure.
       1. If the pool shrinks below the configured min size, create new VMs from the infrastracture to replenish the pool.
       1. This functionality could be completely decoupled from the `machine-controller-manager`, which can simply expect this pool to be _somehow_ maintained. We could even use a shared reserve excess capacity garden shoot cluster as this VM pool.
1. If such a machine pool is defined/configured
   1. When a `Machine` is deleted, don't delete the VM. _Return_ it to the pool instead.
   1. When a `Machine` is created, don't create a new VM. _Reclaim_ a VM from the pool if it is not empty.
1. If such a machine pool is not defined/configured (or if the machine pool is empty, possibly), create VMs exactly the way it is being done now.
1. If such a machine pool is not defined/configured, delete the VMs exactly the way it is being done now.
1. Introduce a mechanism to replace the `kubelet` configurations whenever a VM is _reclaimed_ from or _returned_ to the pool .
   1. A shorter term solution could be to just use the pool while creation and not during deletion as the scheduling latency while scaling up the cluster will still be solved.

### Limitations

- The sharing of the reserve excess capacity will be restricted to the  shared infrastructure credentials.
- At the worst case, it might also be restricted to the shared VPC.

**Comment by vlerenc** [comment]
Thanks for the suggestion. However, it seems too much effort (then we rather not have excess capacity) and also technically not feasible: I am not sure of other infrastructures, but in AWS a VM is bound to the subnet, so you can't even move it within one VPC. You can attach another NIC, but the primary one remains primary. Gardener seeds, as a concrete use case, anyways use dedicated VPCs.

**Comment by amshuman-kr** [comment]
> However, it seems too much effort

Agreed. We have enough on the plate of `machine-controller-manager`.

> (then we rather not have excess capacity)

That will be much effort too (at least removing totally).

> also technically not feasible: I am not sure of other infrastructures, but in AWS a VM is bound to the subnet, so you can't even move it within one VPC. You can attach another NIC, but the primary one remains primary. Gardener seeds, as a concrete use case, anyways use dedicated VPCs.

For now, yes. But we are in no position to do this (even if feasible technically) any time soon. We can take a relook when the current topics are addressed. Not everything in the status quo (number of seeds, dedicated VPCs) need be immutable.

**Comment by vlerenc** [comment]
But also moving between subnets isn't possible on AWS (afaik).
Anyway, let's close the ticket now, please. Too far away at best.

**Comment by amshuman-kr** [comment]
> But also moving between subnets isn't possible on AWS (afaik).

I was thinking about a couple of work arounds but they are really that. Ugly work-arounds.

> Anyway, let's close the ticket now, please. Too far away at best.

Agreed. Too much work and too far away even at best. Closing.
