### ISSUE TITLE
Improve the sorting of machines while scaling down

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#422]
## Improvement
Currently, MCM sorts the machines based on `machine-phase` and `priority`, basically unhealthy machines and lower-priority machines are preferred while scale-down.  We should probably improve the sorting to include more parameters, may be timestamps.

cc @amshuman-kr @prashanth26

**Comment by hardikdr** [comment]
@amshuman-kr Can you please elaborate your suggestions/inputs on sorting?

**Comment by vlerenc** [comment]
Thanks for following up. Timestamps sound good. Are we preferring to replace the older or newer machines by this? Maybe the older as they may be more likely to be shut down anyway by the IaaS one day?
