### ISSUE TITLE
Restore ACID properties on MCM

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#423]
## Issue

* Currently the MCM loses state on MCM restarts. 
* Also the Machine and machine-set controller have races while creating/deleting.

## Solution

Reenable transaction ACID properties for machine creation/deletion.

**Comment by hardikdr** [comment]
A similar suggestion pointed here for deletiion[#421 ], is also required for the machine creation-flow. We should make a listVM() call to verify real-VM-state, before both creation and deletion.
