### ISSUE TITLE
Improve the roll out process 

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#425]
## Issue
Currently, during the machine-rollout, if the creation of machines in new machine-set fails then they are terminated and `immediately` replaced by creating a new one. Although the deletion-call of these new-machines might not have thrown any error, the termination of the machine could either fail later or take a long time. In this case, the guarantee of `Desired+maxSurge` could be violated for the stakeholders. 

## Possible Solution:
Explicitly during roll-outs, MCM should wait till the `Terminating` machines are gone first and only after then create a fresh machine. 
We should probably also control the number of creation/deletion calls on failure, to avoid hitting the rate-limit issues.

**Comment by hardikdr** [comment]
We should also investigate if we can make use of `Spec.ProgressDeadlineSeconds` field to timeout the ongoing upgrade process and how worker-controller could resume it.

**Comment by zuzzas** [comment]
I've run into this numerous times on a couple of cloud platforms with tight resource quotas.

**Comment by hardikdr** [comment]
Currently, Gardener disables the cluster-autoscaler while machine roll-out is active. The absence of cluster-autoscaler may turn out to be critical if roll-out is stuck for a longer duration[may quota/infra issuues], and workload demands scale-up or scale-down of the cluster.  
- We should probably consider the possibility to keep autoscaler running while upgrades are on-going, and make autoscaler aware/ignore the rolling MachineDeployments, while it acts on the rest of the healthy MachineDeployments. 
cc @rfranzke @rewiko

**Comment by prashanth26** [comment]
This issue should be resolved by https://github.com/gardener/machine-controller-manager/commit/423962aba5504c18d2604bf534ab4bb5dd4053cb. Please reopen if you see it again. 
/close
