### ISSUE TITLE
Delete a special node by node name

### ISSUE THREAD

**Issue by qiffang** [gardener/machine-controller-manager#435]
**What would you like to be added**:
Hi @rfranzke , sorry to bother you.
I want to scale in the worker number by deleting a special vm (aws ec2)  by the node name or ec2 name.
What should I do? 

**Why is this needed**:
I deploy statefulset in shoot cluster and 1 pod with 1 vm.
When i update the replica of statefulset, the pod will be scaled in by statefulset. And I want to delete the special vm which running the deleted pod by  ec2 name or node name.

Thanks

**Comment by rfranzke** [comment]
@qiffang can you confirm that this is the same problem already discussed in #390 ? If no, please elaborate further.

**Comment by qiffang** [comment]
Hi @rfranzke 
Thanks you for response.
But i just want to delete a special vm, but https://github.com/gardener/machine-controller-manager/issues/390 seems that it will replace the old vm with the new VM.


For now, there will be 3 machinedeployments in 3 available zones, but i can not specify the machinedeployment which i want to scale in the vm numbers.

**Comment by rfranzke** [comment]
Hm, why is this needed? VMs are treated by Gardener like pods, ephemeral. What's the use case?
@hardikdr @prashanth26 this is not possible today, right?

**Comment by qiffang** [comment]
Thanks @rfranzke 
When i check the source code of machine-controller-manager, i found machineset will delet machines by priority of machines.
So I found a way by adding a machine priority(default is 3, and i will set a special machine as 0 when i want to delete it).

Another questions, i want to set the ec2 of aws `terminal protection as true` when gardener startup ec2.  is it possible for now?
Thanks

**Comment by rfranzke** [comment]
@hardikdr @prashanth26 @ggaurav10 as actual MCM maintainers, could you please take over?

**Comment by hardikdr** [comment]
Hi @qiffang , you can use the machine-priorities to decide which machine should be scaled down next. 

>When i check the source code of machine-controller-manager, i found machineset will delet machines by priority of machines.
>So I found a way by adding a machine priority(default is 3, and i will set a special machine as 0 when i want to delete it).

- It's not possible at the moment to configure it directly via AWSMachineClass, you will have to make necessary changes in the provider code path. - https://github.com/gardener/machine-controller-manager/blob/master/pkg/driver/driver_aws.go#L59

**Comment by qiffang** [comment]
@hardikdr  @rfranzke 
Thanks very much.

- I will decrease machine-priorities by machine-controller-managet client to decide which machine i want to scaled down.

- For adding `terminal protection` for ` aws ec2`, i will call `aws sdk` to set `terminal protection` after `aws ec2` is startup by CMC.

Do you think it is ok?

**Comment by hardikdr** [comment]
So as of now, MCM does support selective scale-down with machines with lesser priority are deleted first. For that, you should probably add independent automation of reducing the machine-priority dynamically and then trigger scale-down. 

- Btw this could also be achieved by using cluster-autoscaler with MCM. Basically autoscaler will choose the empty machine first for the scale-down, and instruct MCM to delete that specific machine. 
    - https://github.com/gardener/autoscaler

**Comment by prashanth26** [comment]
I am closing this issue if it has been resolved.
