### ISSUE TITLE
Create metrics for labels from machinedeployments and machineclasses

### ISSUE THREAD

**Issue by supreethrao** [gardener/machine-controller-manager#443]
**What would you like to be added**:
machine controller manager provides useful metrics around machine deployments. However, it will be useful to also have metrics for labels on the custom resources. The labels can have useful information like the version of the resource amongst others and would hence be useful to have them as metrics, similar to [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) for k8s resources. 

**Why is this needed**:
Serves different purposes. Some of the reasons could be 
1. Having the information from labels (e.g version) displayed on a status dashboard
2. In alerting if machine deployments across different AZs are not the same 

I am happy to work on this and add this feature if deemed useful

**Comment by hardikdr** [comment]
Thanks @supreethrao for suggesting it.  Please feel free to pick this up.

**Comment by prashanth26** [comment]
Close in favour of https://github.com/gardener/machine-controller-manager/issues/211#issuecomment-809929347.
