### ISSUE TITLE
Upgrade machine-controller-manager

### ISSUE THREAD

**Issue by qiffang** [gardener/machine-controller-manager#446]
Hi @rfranzke  
I use gardener to manage our kubernetes clusters.
I seems that this PR (
 https://github.com/gardener/machine-controller-manager/pull/414) support local ssd for GCP. I just want to upgrade machine-controller-manager, how should i update the image version of machine-controller-manager?

**Comment by prashanth26** [comment]
Hi @qiffang ,

We usually create images on PRs on successfully reviewing the PR. The image name is usually of the following format `tagged eu.gcr.io/gardener-project/gardener/machine-controller-manager:v0.27.0-dev-{last-commit-hash-on-PR}`. In this case it's tagged 

`eu.gcr.io/gardener-project/gardener/machine-controller-manager:v0.27.0-dev-5caf330d053a56054e099b45eb0a303da834a9f9`

Also the new major release in MCM - `0.28.0` will contain this feature. Hope this helps.

**Comment by qiffang** [comment]
Hi @prashanth26 
Thanks for your response.
But i need to a way to update the image version(I have build the latest image) in the gardener.

**Comment by prashanth26** [comment]
Okay. That would depend on the gardener extension provider that you are using. If you are using aws for eg - you would have to update the `https://github.com/gardener/gardener-extension-provider-aws/blob/master/charts/images.yaml#L24` to the above version and rebuild the provider extension image and deploy it.

**Comment by prashanth26** [comment]
Does the above, answer your question?
