### ISSUE TITLE
Avoid draining of NotReady nodes

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#448]
**What would you like to be added**:
Avoid draining of nodes in `NotReady` state. 

**Why is this needed**:
Draining of nodes in a `NotReady` state sometimes ends up waiting for up to drain timeout as the Kubelet might be stuck. So in cases where the node isn't ready, a force delete might be preferred.

**Comment by zuzzas** [comment]
I'd like to take on this one. Coding and testing right now.

**Comment by rfranzke** [comment]
Awesome, thanks @zuzzas

**Comment by hardikdr** [comment]
Re-opening the issue, as there seems to be a further scope of improvement on top of the #450.
1. The current implementation applies complete drain-timeout if the node is `NotReady` for less than 5 mins. We should probably follow the suggestion made [here](https://github.com/gardener/machine-controller-manager/pull/450#issuecomment-617550251).

1.  Changes could potentially be migrated to machine.go.

**Comment by prashanth26** [comment]
Closing this is favour of https://github.com/gardener/machine-controller-manager/issues/579#issuecomment-809925138
