### ISSUE TITLE
Add special handling for draining nodes with Istio

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/machine-controller-manager#459]
**What would you like to be added**:
Draining a worker node (i.e. after Kubernetes update) where the only pod of the `istio-galley`or `istio-citadel` deployments is running fails (even after 3h). MCM tries repeatingly to delete these pods but without any change.
In this case a special handling is needed to conform with the PDB of Istio. First these two deployments have to be scaled up and after start of the new pods on other nodes scaled down again.

```
k scale --replicas=2 deployment/istio-galley
k scale --replicas=2 deployment/istio-citadel
# wait for pod deployments
k scale --replicas=1 deployment/istio-galley
k scale --replicas=1 deployment/istio-citadel
```

**Why is this needed**:
For example if Kubernetes is updated, new worker nodes are created, but the draining of the old nodes fails for the above mentioned pods, because of the PDB of istio:
```
❯ k get pdb -n istio-system
NAME                     MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
ingressgateway           1               N/A               0                     3h12m
istio-citadel            1               N/A               0                     3h12m
istio-galley             1               N/A               0                     3h12m
istio-pilot              1               N/A               1                     3h12m
istio-policy             1               N/A               0                     3h12m
istio-sidecar-injector   1               N/A               0                     3h12m
istio-telemetry          1               N/A               0                     3h12m
```
There is was issue raised at the istio project, but it was closed without any action.
See https://github.com/istio/istio/issues/12602

The recommended solution is as described above to scale up the deployments temporarily (see also https://github.com/istio/istio/issues/12602#issuecomment-555191475)

**Comment by MartinWeindel** [comment]
Situation seen on a cluster:
```
❯ k get mach
NAME                                                    STATUS        AGE
shoot--berlin--vv-dev-1-worker-vv-z1-65d7598b76-54lsn   Running       95m
shoot--berlin--vv-dev-1-worker-vv-z1-65d7598b76-mckmb   Running       93m
shoot--berlin--vv-dev-1-worker-vv-z1-86c8f9d765-jfxvl   Terminating   3h2m
shoot--berlin--vv-dev-1-worker-vv-z1-86c8f9d765-l2kdx   Terminating   3h2m
shoot--berlin--vv-dev-1-worker-vv-z1-86c8f9d765-lmqvs   Terminating   3h2m

❯ k get node
NAME                                                    STATUS                     ROLES    AGE    VERSION
shoot--berlin--vv-dev-1-worker-vv-z1-65d7598b76-54lsn   Ready                      <none>   97m    v1.17.5
shoot--berlin--vv-dev-1-worker-vv-z1-65d7598b76-mckmb   Ready                      <none>   95m    v1.17.5
shoot--berlin--vv-dev-1-worker-vv-z1-86c8f9d765-jfxvl   Ready,SchedulingDisabled   <none>   3h4m   v1.16.9
shoot--berlin--vv-dev-1-worker-vv-z1-86c8f9d765-l2kdx   Ready,SchedulingDisabled   <none>   3h4m   v1.16.9
shoot--berlin--vv-dev-1-worker-vv-z1-86c8f9d765-lmqvs   Ready,SchedulingDisabled   <none>   3h4m   v1.16.9
```

**Comment by rfranzke** [comment]
Probably it should have a way lower drain timeout if it detects PDBs that have `minAvailable=1` for deployments with only `1` replica?

**Comment by MartinWeindel** [comment]
If you drain the nodes forcefully, don't you interrupt istio functionality until the new pods have (hopefully) started on other nodes?

**Comment by vlerenc** [comment]
This happened again yesterday. However, I don't think we can decide to scale out replicas. That is not our decision to make and not all workload may cope with that (multiple replicas) - we can't really know, can we?

I would rather argue that replica=1 and pdb=0 is nonsense for automated cluster operations. We do ignore PDBs during hibernation and termination now, right @prashanth26 and @hardikdr? Maybe we should do the same (in these and only these cases) when we do a rolling update as well? When GKE rolls, it ignores just everything after a brief grace period of only 5 mins, I believe to remember. Then again, there are other "constructed cases" with affinities, taints&tolerations, etc. that may have the same effect like replicas=1 and pdb=0. I guess, rather than handling this special case, a shorter grace period would make sense? Also, what happened in https://sap-cp.slack.com/archives/GRF0JR6G3/p1588347716248500? I don't see indication of a rolling update? How come 2 out of 3 zone worker pools had all disabled scheduling? Were the Istio components that blocked drain responsible and if so how?

P.S.: We might want to involve people like @piotrmiskiewicz from https://kyma-project.io bringing Istio with them and ask them to change the PDBs if possible. As it is right now, Gardener's full automation and Istio's PDB settings create problems.

**Comment by prashanth26** [comment]
> I would rather argue that replica=1 and pdb=0 is nonsense for automated cluster operations. 

I would agree with this. Building such logic into the drain is complicated and might effect other workloads. 

> When GKE rolls, it ignores just everything after a brief grace period of only 5 mins, I believe to remember. Then again, there are other "constructed cases" with affinities, taints&tolerations, etc. that may have the same effect as replicas=1 and pdb=0. I guess, rather than handling this special case, a shorter grace period would make sense? 

Yes, I agree with this as well. Maybe we should default the drain timeout to something like 5-10mins. And maybe add support for this to be configurable in the future.  But the default to be a smaller value than 2hours as it is today.

**Comment by hardikdr** [comment]
I would also agree, we should fix https://github.com/gardener/gardener/issues/1843, and let the user decide if they want larger `drainTimeout`


>Also, what happened in https://sap-cp.slack.com/archives/GRF0JR6G3/p1588347716248500?

I think this is an issue at Autoscaler, it seems to be ignoring the `Unschedulable` nodes and node-groups will all the `unschedulable` nodes could suffer from no-scale-up. I have created an issue to track this- https://github.com/gardener/autoscaler/issues/36


>I don't see indication of a rolling update? How come 2 out of 3 zone worker pools had all disabled scheduling? Were the Istio components that blocked drain responsible and if so how?

Not sure, how was the scheduling disabled for them, it could possibly be user-initiated but need to be verified. MCM/CA didn't seem to taint them, as they were not marked for deletion either.

**Comment by hardikdr** [comment]
As drainTimeout is now configurable, users can decide for themselves, and as we can't do much in MCM to solve this, should we close this issue?

**Comment by prashanth26** [comment]
Yes, agreed. 

Closing in favor of configurable drain timeouts.
