### ISSUE TITLE
Limit the Random Hash in the MachineSet Name

### ISSUE THREAD

**Issue by vpnachev** [gardener/machine-controller-manager#461]
**What would you like to be added**:
Currently, MachineSet names are with variable length of the random hash 
The MCM is also not limiting the random hash in the machineset names, ref https://github.com/gardener/machine-controller-manager/blob/8ec2a7fc26952d12b270604040c0e5795ca90e67/pkg/controller/deployment_sync.go#L306

**Why is this needed**:
To allow proper assumption of the machine object names based on the project, shoot and worker pool names.

**Comment by prashanth26** [comment]
Assigning the issue to Samarth Deyagond

**Comment by vpnachev** [comment]
Then
/assign @AxiomSamarth

**Comment by hardikdr** [comment]
I guess he is not part of the org yet, needs to be added.

**Comment by AxiomSamarth** [comment]
@prashanth26 @hardikdr In this context, here are few observations of mine.

- The issue description of CSI Driver failing has a point that K8s does not allow creation of CSINode objects with len(nodeID)>128. I also created the machine deployment with names with length longer than 128 characters, I saw no failures as such. So, is it something very specific to the CSINode object's nodeID attribute?

- The machine set name follows the pattern of shoot--<projectName>--<shootName>-<workerName>-<zone>-<templateHash> and considering the character limit of the project name(10), shoot name(14), worker name(15), the entire name will not exceed 128 characters.

- I feel that, if we are going to add any limits then it must be at the machine deployment level which might be possibly be a breaking change. So, please provide your inputs on how to go about.

**Comment by prashanth26** [comment]
@vpnachev - Do you have more inputs on how and why the limits were hitting and how we could avoid this?

**Comment by AxiomSamarth** [comment]
> @vpnachev - Do you have more inputs on how and why the limits were hitting and how we could avoid this?

@prashanth26 The below was his input - 

_Usually objects with `generateName` are appended with a random hash string which has limited length, e.g. 5 or 8 characters. With MCM there is no such limitation, thus the machine name length is unpredictable. A simple fix of the above is just to trim the length of the randomly generated string to 5._

**Comment by vpnachev** [comment]
You cannot fix the CSI issue in the MCM. The NodeID also contains the GCP project id and the zone. The project id is limited to 30 characters and the longest zone name is 25 currently. The NodeID also contains some metadata `projects/<project-id>/zones/<zone>/instances/<vm-name>` which adds a 25 more characters. So, for the machine name left less than 58 characters some of them are occupied by the Gardener project name, shoot name and worker  pool name. 

But if you limit the length of the random hash, it will help to reduce the occurrences of the CSI issue till it is fixed upstream.

**Comment by AxiomSamarth** [comment]
Okay! PR #500 implements that quick change to limit the random hash to 5 characters
