### ISSUE TITLE
Update Status on machine object right before machine creation

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#466]
**What would you like to be added**:
In cases like Azure, machine creation is an asynchronous call. We should update the status of the machine object before making this call probably. 

**Why is this needed**:

**Comment by hardikdr** [comment]
Can this be combined with https://github.com/gardener/machine-controller-manager/issues/444 ? - There we'll have to anyways discuss the state-management, this could also be considered as a requirement.

**Comment by prashanth26** [comment]
closing in favor of https://github.com/gardener/machine-controller-manager/issues/444.

/close
