### ISSUE TITLE
Detect unavailable network

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/machine-controller-manager#469]
**What would you like to be added**:

Provide a means to detect broken networking on a node (especially for calico).  

For instance we observed the following logs in the `calico-node` daemon:
```
bird: Mesh_10_250_10_60: Socket error: bind: Address in use
bird: Mesh_10_250_19_13: Socket error: bind: Address in use
bird: Mesh_10_250_21_169: Socket error: bind: Address in use
```
However the Node is still shown as Ready. 

MCM to date checks the following conditions on the Node
 - `KubeletNotReady`
 -  `ReadOnlyFS`
 -  `DiskPressure`
 -  `KernelDeadlock`  

Possibly, the MCM should also check for the condition type `NetworkUnavailable` (if the [NPD](https://github.com/kubernetes/node-problem-detector)  is deployed) and should replace the node after a certain threshold, if the Node continues to have problems with Networking.

The problem with relying on the NPD is, that it seems not to properly detect Calico problems in all cases

In the case described above, even though `calico-node` logs errors, the NPD does not detect an abnormal condition.
```
NetworkUnavailable            False   Wed, 27 May 2020 23:07:26 +0200   Wed, 27 May 2020 23:07:26 +0200   CalicoIsUp                      Calico is running on this node
```

I think detecting such calico issues would be very helpful.

I currently see two general approaches how to solve this issue
 -  (1) build logic in the MCM that checks `calico-node`, `felix` & `bird` for abnormalities
-  (2) make the MCM also consider the `NetworkUnavailable` condition on the Node.  Describe the issue in the [NPD](https://github.com/kubernetes/node-problem-detector)  and try to fix / contribute to an upstream fix.

I think it would make sense to go with option (2)

**Why is this needed**:

Properly detect network problems with nodes.

thanks @hardikdr  for already investigating

**Comment by rewiko** [comment]
Hello, 

I might have missed something but it seems the machine health checks all the condition available [link](https://github.com/gardener/machine-controller-manager/blob/737093bfdaaf35407bb7fa3c49a40fb0b0ae2b1f/pkg/controller/machine.go#L936). 

We are using NodeCondition to make sure we can control the rolling deployment of machines. 
We have a component on our AMI which update a node condition. In our case, that's `NodeInitialization` set to True at startup and then set to False when we have all the daemonset and network/network policies/CNI ready. 
So far machine-controller-manager is seeing the machine as not ready until all conditions are set to False, except `NodeReady`.

**Comment by danielfoehrKn** [comment]
> I might have missed something but it seems the machine health checks all the condition available 
I think you are right.

> I think machine-controller-manager should be agnostic of any CNI and rely on NodeCondition.
That's should probably be fixed on calico-node, and should detect the issue and update the NodeCondition.

Agree that MCM should only rely on the Node condition.  
I though that the condition type `NetworkUnavailable` comes from the NPD, but as you suggest it seems to be originating from the `calico-node`.

@prashanth26  WDYT is the way forward here?

**Comment by rewiko** [comment]
Just for completeness https://github.com/projectcalico/calico/pull/2269

**Comment by prashanth26** [comment]
Hi @danielfoehrKn ,

I think as @rewiko mentioned above, this is already configurable in the MCM here - https://github.com/gardener/machine-controller-manager/blob/master/kubernetes/deployment/in-tree/deployment.yaml#L32. I think adding `NetworkUnavailable` to this list should detect such nodes as well. WDYT?

**Comment by prashanth26** [comment]
@danielfoehrKn 's message.

Agree that the `NetwrorkUnavailable` should be added

Still, the calcio-node did not detect the problem. But I cannot easily reproduce the error to open a comprehensive issue on the calico side. I think for now it would be already good to check for that condition as well.

**Comment by prashanth26** [comment]
@danielfoehrKn - So basically your idea is to update the NPD to detect this condition as well right? as mentioned in (2) above. 

@hardikdr - WDYT?

**Comment by rfranzke** [comment]
The problem is that even if NPD reacts on this condition then nobody is actively maintaining it. Calico sets it to `False` when it starts up, but nobody would set it to `True` in case calico fails, right?

**Comment by danielfoehrKn** [comment]
I would expect that `calico-node` does not only initialize the condition once it successfully started, but also updates it in case of problems during the execution. But that [does not seem to be the case](https://github.com/projectcalico/node/pull/89/files).
Hence monitoring the `NetworkUnavailable` Condition is of little use atm.

So either 
 - Calico updates the condition if an error occurs
 - The NPD is able to detect Calico problems and can update the condition

**Comment by danielfoehrKn** [comment]
Opened [issue on calico-node](https://github.com/projectcalico/node/issues/519#issuecomment-645479043)

**Comment by zanetworker** [comment]
A more specific issue also opened on calico-node: https://github.com/projectcalico/node/issues/522

**Comment by hardikdr** [comment]
>Possibly, the MCM should also check for the condition type NetworkUnavailable

The NodeConditions, which MCM should react on are configurable now here: https://github.com/gardener/machine-controller-manager/blob/master/kubernetes/machine_objects/machine-deployment.yaml#L34.
If we agree, or if you suggest, happy to add `NetworkUnavailable` in the criteria, and the machine will be replaced with such networking-issues.

If not, the other/major part of the issue sounds more like a bug/behavior with how calico reports the node-condition, I don't think MCM can do much there, we could close this issue then.

**Comment by danielfoehrKn** [comment]
> if we agree, or if you suggest, happy to add NetworkUnavailable in the criteria, and the machine will be replaced with such networking-issues.

+1 from me. Even though calicos behaviour is not optimal here, other network plugins might set this correctly. 
I do not think it can harm us to also check this condition.

**Comment by rewiko** [comment]
We have set NetworkUnavailable on our config, useful with cilium which set to true and start-up and false when cilium is initialized.

**Comment by rewiko** [comment]
Merged on master, waiting for the release to close this issue.

**Comment by prashanth26** [comment]
Hi @rewiko ,

We will make a release of the MCM soon. Positively by early next week. Just FYI.

**Comment by rewiko** [comment]
We could even close this issue now, up to you :)

**Comment by hardikdr** [comment]
/close
Then we close it as the [PR](https://github.com/gardener/machine-controller-manager/pull/543) is merged, and release of the change is inevitable ;)
