### ISSUE TITLE
Driver backend should be pluggable

### ISSUE THREAD

**Issue by mvladev** [gardener/machine-controller-manager#47]
`MCM` should not vendor any cloud-specific code. All calls to the underlying IaaS providers should happen over [CRI-styled](https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/kubelet/api/v1alpha1/runtime/api.proto) `gRPC` remote backend.

This will allow to quickly update the implementations without spending countless hours battling with dependencies. Ideally you would deploy the `MCM` in a `Pod` and as a sidecar container - the cloud-specific implementation.

**Comment by ggaurav10** [comment]
PR #102, which is still a work in progress(WIP), is opened for review and suggestions.

**Comment by ggaurav10** [comment]
We are evaluating different approaches to achieve this. Refer #178 for details.

**Comment by prashanth26** [comment]
Closing this issue, as a more elaborate duplicate issue exists. Refer - https://app.zenhub.com/workspace/o/gardener/machine-controller-manager/issues/180
