### ISSUE TITLE
Disable scale-down during cluster-rollouts.

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#472]
**What would you like to be added**: 

As discussed here https://github.com/gardener/autoscaler/issues/48#issuecomment-640600405 , we should add the annotation `cluster-autoscaler.kubernetes.io/scale-down-disabled` on the new machine-sets during roll-outs. 
- This will allow the system to keep CA running even during rolling-updates.

**Comment by prashanth26** [comment]
Points to remember during the implementation refer - https://github.com/gardener/autoscaler/issues/48#issuecomment-640600405
