### ISSUE TITLE
Move the drain logic out of the machine loop

### ISSUE THREAD

**Issue by mvladev** [gardener/machine-controller-manager#48]
The drain logic should be moved in a completely separate controller. That controller will only handle an annotation and finalizer.

**Comment by prashanth26** [comment]
Earlier we had copied over the code for Kubernetes drain logic. However, now drain is available as a library, Refer: https://github.com/kubernetes/kubernetes/pull/72827. 

Two other issues we see in the current copied over drain are the following, which we need to investigate if has improved in the new library,
1. We observed that drain was not adhering the timeouts exactly.
2. We saw errors while trying to update the node objects without retry mechanisms.

**Comment by prashanth26** [comment]
Refer - https://github.com/gardener/machine-controller-manager/issues/490#issuecomment-660003060.
