### ISSUE TITLE
MachineDeployment would not get processed due to potential race condition

### ISSUE THREAD

**Issue by aylei** [gardener/machine-controller-manager#485]
**What happened**:
Machine was not get created with MachienDeployment replica set to 1

```
$ kubectl get machinedeployment -n shoot--e2e--1a161242
NAME                               READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--e2e--1a161242-336a2248-z1   1       1         1            1           25m
shoot--e2e--1a161242-5531f291-z1           1                                  25m
shoot--e2e--1a161242-5531f292-z1           1                                  25m
```

Log of MCM
```
kubectl -n shoot--e2e--1a161242 logs -f machine-controller-manager-56d98b5f7c-pfz5m | grep shoot--e2e--1a161242-5531f292-z1
I0713 06:05:47.627358       1 gcpmachineclass.go:211] Successfully added/removed finalizer on the gcpmachineclass "shoot--e2e--1a161242-5531f292-z1-430c0"
I0713 06:05:49.527895       1 deployment.go:448] Processing the machinedeployment "shoot--e2e--1a161242-5531f292-z1" (with replicas 1)
I0713 06:05:49.527994       1 machine.go:933] No secret "&SecretReference{Name:shoot--e2e--1a161242-5531f292-z1-430c0,Namespace:shoot--e2e--1a161242,}": found for MachineClass "shoot--e2e--1a161242-5531f292-z1-430c0"
I0713 06:05:50.226619       1 secret.go:132] Successfully added/removed finalizer on the secret "shoot--e2e--1a161242-5531f292-z1-430c0"
```

**What you expected to happen**:
Machine count matches the desired replicas of MachineDeployment

**How to reproduce it (as minimally and precisely as possible)**:
Create MachineDeployments frequently and it may be reproduced

**Anything else we need to know**:
1. The secret is get from the local informer, which does not provide consistent read
2. If the secret is not watched by the informer, the controller should have retried the reconciliation but in fact it considers the reconciliation is completed because secret not found does not return any error 

**Environment**:
I'm using machine-controller-manager v0.29.0

**Comment by hardikdr** [comment]
Very likely be related to this: https://github.com/gardener/machine-controller-manager/issues/430 .
- Probably a minor change and but needs to be fixed yet.

**Comment by prashanth26** [comment]
Hi @aylei ,

We think that this issue would be fixed with this PR - https://github.com/gardener/machine-controller-manager/pull/495. Please reopen this PR if the problem persists. Closing it for now. 

/close
