### ISSUE TITLE
MCM to mark terminating nodes

### ISSUE THREAD

**Issue by guydaichs** [gardener/machine-controller-manager#488]
**What would you like to be added**:

When MCM replaces nodes (unhealthy node termination, node rolling updates, ...), nodes that are being terminated should be marked in some way (e.g. annotation) to reflect the reason of their termination. 

**Why is this needed**:
End-users can setup monitoring for the progress of node rolling updates. If PDBs are used, end-users can automate removal of PDBs from pods that are running on nodes which are being terminated due to health issues.

**Comment by hardikdr** [comment]
Sounds like a good idea to me to have an indication on node-object, whenever it's being terminated, likely due to health-conditions.

**Comment by prashanth26** [comment]
I got the information that you are working on a fix for this. Hence assigning you to the issue. 

/assign @guydaichs

**Comment by guydaichs** [comment]
Hi @prashanth26. Yes, I'm working on this. I noticed that there's already a mechanism for syncing the machine config with a node annotation. However, in my case, I want the annotation to capture a certain transition, and not the current state. 

So, I was thinking to annotate the node in the `machineDelete` method, and reflect `machine.Status.CurrentStatus.Phase` if it's not `Terminating`. For example, in case of replacement due to health issues, the node would be annotated with `node.machine.sapcloud.io/termination: failed`, until it's actually removed from the cluster. 

WDYT?
