### ISSUE TITLE
Trigger rolling update of machines without changing machine class reference

### ISSUE THREAD

**Issue by rfranzke** [gardener/machine-controller-manager#517]
**What would you like to be added**:
It would be nice to have a trigger for a rollout of the machines without the necessity to change the machine class reference.

**Why is this needed**:
Apply updates/changes that are only done when the machine is created/booted the first time. 
Currently in gardener rolling update for a k8s version change, we use the hack of changing the machineClass name (which is not correct) to make MCM do rolling update. We want to make MCM trigger rolling update without changing the machineClass reference.

/cc @guydaichs

**Comment by hardikdr** [comment]
Interesting.
Btw this can be achieved if the same MachineClass is updated with new values. The values will be in effect only when the new machine is created or old one is deleted.

**Comment by zuzzas** [comment]
We're doing it by changing the `.spec.template.metadata.annotations`. Basically, adding anything or changing any annotation there will trigger the rollout of new Machines.

Same as the Deployment object in Kubernetes.

**Comment by himanshu-kun** [comment]
/close 
as there are other ways of triggering rolling update as mentioned in the above comment https://github.com/gardener/machine-controller-manager/issues/517#issuecomment-700663951
