### ISSUE TITLE
Investigate how to respect PDB (Pod Disruption Budget)

### ISSUE THREAD

**Issue by vlerenc** [gardener/machine-controller-manager#52]
As discussed, it seems the machine controller manager (reusing the drain logic of `kubectl`) does not respect the pod disruption budget (in contrary to what the official documentation https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node is saying).

A few questions:
- Are we sure we really took all logic from `kubectl`? Maybe we missed the critical bits, because the documentation above is pretty explicit in that it respects the PDB?
- What happens with multiple `kubectl` drains in parallel? Is the CLI adhering to the documentation at all/in general?
- Is the eviction API really an option? I would refrain from it (and even rather call `kubectl` if I have to) if there are anyhow plans to move the drain logic to the Kubernetes backend.

**Comment by prashanth26** [comment]
Hi Vedran,
                 Sorry I had misconfigured the PDB and hence the previous experiment gave wrong results. My mistake, sorry about that. I re did the experiments and it works fine now. 

I took the scenario explained earlier with
- A machineDeployment with replicas:5, maxSurge:0, maxUnavailable:3 => available:2
- A podDeployment with replicas:5, maxSurge:0, maxUnavailable: 1 => available:4
- And the PDB of 4 available replicas was satisfied. 
-I re-did the same with pod available of 3, and it was also satisfied and this time the pods available went down from 4 to 3. Hence PDB seems to be respected.

The drain seems to respect the PDBs. The machineDeployment upgrade seems to be working perfect. However we may need to enhance the drain timeout (currently configured to 5mins), as the controller forcefully deletes any machine that doesn't complete the drain in the configured timeout.

Regards,
Prashanth

**Comment by vlerenc** [comment]
Thanks for the info, so are we closing this ticket (or reusing it for the timeout question)?

In case the drain is faster, we agreed to do not wait for the timeout, but terminate the machine immediately, right? I remember we talked about it, but do we have it already in the MCM or should we "refurbish" this ticket to that purpose (or open a new one)?

**Comment by prashanth26** [comment]
Yes we have done it already in MCM. When the drain is successful, we terminate the machines instantly. However, when drain fails/timeouts we wait/re-try for a timeout period (default 5mins), after which we forcefully terminate the machine. 

Just the concern is that this timeout may not suffice if several machines are trying to drain in parallel and the PDB is stopping the drain from occurring. We might need to figure out a more meaningful timeout period.

**Comment by vlerenc** [comment]
Yes, I see. That's a problem I don't know how to solve. I am not sure others have solved that either (kops just waits 5 minutes and terminates the machines then at the latest). I believe GKE takes the instance groups and does whatever you tell it to do (max down), but otherwise the machines are gone (maybe even immediately? I have forgotten since I did that last time in GKE).

Hmm... what means would we have? Really inspect the workload in detail? That seems like unreasonable effort. We should put that into the contract/SLAs, I would say (5 minutes). Agreed?

What we could do in addition to mitigate the issue: ask the user in the dashboard to configure the maxUnavailable parameter per worker pool. What do you think @rfranzke, @dkistner, @holgerkoser, @petersutter, @grolu? What is the current default anyhow? I guess 1? That will suffice for a while.

**Comment by prashanth26** [comment]
Yes. Looks good to me.
