### ISSUE TITLE
force-deletion label is not documented

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/machine-controller-manager#529]
**What would you like to be added**:
As developer I would like to be able to find documentation about the `force-deletion` label - for example what is the difference with the normal deletion; details wrt to Pod eviction/deletion; details about Pods with volumes and how they are handled, etc.

/priority normal
/area documentation
/kind task

**Comment by hardikdr** [comment]
I tried adding a bit of documentation via FAQ: https://github.com/gardener/machine-controller-manager/pull/530 .
