### ISSUE TITLE
OpenStack: add support for subnet specifying

### ISSUE THREAD

**Issue by kayrus** [gardener/machine-controller-manager#535]
**What would you like to be added**:

Currently it is only possible to specify the VM network. However a network may contain a list of subnets.

**Why is this needed**:

An end user should be able to specify a subnet, where worker nodes must reside.

**Notes**:

This feature would be a little bit tricky, because nova API doesn't support a subnet in API spec. Thus a neutron port in a specified subnet must be created, then referenced in nova API spec. Also when a VM is deleted, a custom neutron port must be explicitly deleted, since a VM deletion doesn't delete a custom neutron port.

In addition, an end user should be able to create neutron ports in advance, and reuse them for VMs. This should allow to preserve private IPs list for a shoot cluster. In this case a custom neutron port must not be deleted during the VM deletion.

cc @vpnachev  @zuzzas

**Comment by dkistner** [comment]
@MrBatschner and @hendrikKahl are already working on it :)
