### ISSUE TITLE
Add metrics for node replacement to endusers

### ISSUE THREAD

**Issue by schrodit** [gardener/machine-controller-manager#549]
**What would you like to be added**:

When the mcm is replacing a node, due to failing health checks or unhealthy conditions.
It would be great for endusers to have metrics about when and why the mcm has replaced a node. 

This could be related to https://github.com/gardener/machine-controller-manager/issues/140 but with the focus on endusers.

cc @prashanth26

**Comment by hardikdr** [comment]
Related to: https://github.com/gardener/machine-controller-manager/issues/549
