### ISSUE TITLE
Generated machine class name exceeds 63 character limitation

### ISSUE THREAD

**Issue by EmoinLanyu** [gardener/machine-controller-manager#565]
**What happened**:
Our user created a Shoot with multiple worker groups, some worker groups have failed to be created.
After investigation, we found that it is caused by exceed of length limitation of `metadata.name` for corresponding machineclass resources.
Our current way of naming it is `shoot--(project_name)--(shoot_name)--(worker_group_name)--(region_id)--(worker_name)`. And Gardener limits:
- Project name: 10 chars
- Shoot name: 15 chars
- Worker group name: 15 chars

Worker name is auto generated and is usually 5 chars.
**If we sum above numbers up (including word `shoot` and multiple `-`s), at minimum, there are only 3 chars left for `region_id`.**

**What you expected to happen**:
A better naming mechanism for machine class resources that avoids potential exceeding of character limitation.

**How to reproduce it (as minimally and precisely as possible)**:
Create a worker in a worker group whose name is maximum char length, in a shoot whose name is maximum char length, in a project whose name is maximum char length.

**Anything else we need to know**:
Currently we meet this issue on AliCloud. But I suppose it is the same across all cloud providers.

**Environment**:
AliCloud Canary

**Comment by prashanth26** [comment]
Hi @EmoinLanyu ,

But in my understanding, the gardener/extensions prepends and creates the machine classes and MCM just uses it. So I guess the fix would've to be at the extension-provider? no?

**Comment by EmoinLanyu** [comment]
> Hi @EmoinLanyu ,
> 
> But in my understanding, the gardener/extensions prepends and creates the machine classes and MCM just uses it. So I guess the fix would've to be at the extension-provider? no?

Thanks for the quick reply. And yes, this should be decided on extension provider side. Thanks for pointing out. I'll close this issue then. Many thanks!
