### ISSUE TITLE
Avoid draining of Ready Nodes with ReadonlyFilesystem condition being true

### ISSUE THREAD

**Issue by dguendisch** [gardener/machine-controller-manager#579]
**What would you like to be added**:
Similar to #448 the node draining should be skipped if a node has a ReadOnly filesystem. Note that in this case the Node is in Ready state, "just" the `ReadonlyFilesystem` condition is true.

**Why is this needed**:
To speedup deletion of faulty nodes. A node with a readonly filesystem is effectively broken and draining can hardly succeed but unnecessarily prolongs recovery time.

**Comment by hardikdr** [comment]
We could also consider force-deleting the unhealthy machine in general. The long drain is useful only during rollouts when machines are healthy. For an unhealthy machine, the drain is highly likely to be stuck, though we should do due diligence to make sure of not missing any crucial case. 

cc @zuzzas @prashanth26 @AxiomSamarth

**Comment by prashanth26** [comment]
To consider [the following considerations](https://github.com/gardener/machine-controller-manager/pull/450#issuecomment-619503726) while implementing this solution.

**Comment by prashanth26** [comment]
/assign
Assigning to myself, eventually assigned to Himanshu.

**Comment by prashanth26** [comment]
/unassign 

Paused in favour of https://github.com/gardener/machine-controller-manager-provider-aws/issues/24

**Comment by prashanth26** [comment]
/assign 
To himanshu.
