### ISSUE TITLE
mcm least privilege in aws

### ISSUE THREAD

**Issue by zjj2wry** [gardener/machine-controller-manager#584]
**What would you like to be added**:
I want to set the least permissions for machine-controller-manager in AWS. I want to know where I can find AWS IAM policys. thank you very much

**Why is this needed**:

**Comment by rewiko** [comment]
Hello, 

So far that's what we are using on our cluster.
```
resource "aws_iam_group_policy" "machine_controller_manager" {
  name  = "machine_controller_manager"
  group = "${aws_iam_group.machine_controller_manager.id}"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "MachineControllerManagerNonResourceLevelPermissions",
      "Effect": "Allow",
      "Action": [
        "ec2:AllocateAddress",
        "ec2:CancelSpotInstanceRequests",
        "ec2:CreateTags",
        "ec2:CreateVolume",
        "ec2:Describe*",
        "ec2:RequestSpotInstances",
        "iam:CreateServiceLinkedRole",
        "iam:GetInstanceProfile",
        "iam:GetPolicy",
        "iam:GetPolicyVersion",
        "iam:GetRole",
        "iam:GetRolePolicy",
        "iam:ListPolicyVersions",
        "iam:ListAttachedRolePolicies",
        "iam:ListInstanceProfilesForRole",
        "iam:PassRole"
      ],
      "Resource": [
                "*"
      ]
    },
    {
        "Sid": "MachineControllerManagerInstancesActions",
        "Effect": "Allow",
        "Action": [
            "ec2:TerminateInstances",
            "ec2:AttachVolume",
            "ec2:DetachVolume",
            "ec2:DeleteVolume"
        ],
        "Resource": [
            "arn:aws:ec2:${var.region}:${var.aws_account_id}:instance/*",
            "arn:aws:ec2:${var.region}:${var.aws_account_id}:volume/*",
            "arn:aws:ec2:${var.region}:${var.aws_account_id}:security-group/*"
        ],
        "Condition": {
            "StringEquals": {
              "ec2:ResourceTag/${var.tag_key}": "${var.tag_value}"
            }
        }
    },
    {
      "Sid": "MachineControllerManagerRunInstancesWithRequiredTag",
      "Effect": "Allow",
      "Action": [
        "ec2:RunInstances"
      ],
      "Resource": [
        "arn:aws:ec2:${var.region}:${var.aws_account_id}:instance/*"
      ],
      "Condition": {
        "StringEquals": {
          "aws:RequestTag/${var.tag_key}": "${var.tag_value}"
        }
      }
    },
    {
      "Sid": "MachineControllerManagerRunInstancesActions",
      "Effect": "Allow",
      "Action": [
        "ec2:RunInstances"
      ],
      "Resource": [
        "arn:aws:ec2:${var.region}:${var.aws_account_id}:security-group/*",
        "arn:aws:ec2:${var.region}:${var.aws_account_id}:subnet/*",
        "arn:aws:ec2:${var.region}:${var.aws_account_id}:vpc/${var.vpc_id}",
        "arn:aws:ec2:${var.region}:${var.aws_account_id}:network-interface/*",
        "arn:aws:ec2:${var.region}:${var.aws_account_id}:key-pair/*",
        "arn:aws:ec2:${var.region}:${var.aws_account_id}:volume/*",
        "arn:aws:ec2:${var.region}::image/*"
      ]
    }
  ]
}
EOF
}
```

We should probably update the doc, to add IAM roles for each provider. cc: @hardikdr @prashanth26 @ggaurav10

**Comment by zjj2wry** [comment]
> Hello,
> 
> So far that's what we are using on our cluster.
> 
> ```
> resource "aws_iam_group_policy" "machine_controller_manager" {
>   name  = "machine_controller_manager"
>   group = "${aws_iam_group.machine_controller_manager.id}"
> 
>   policy = <<EOF
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Sid": "MachineControllerManagerNonResourceLevelPermissions",
>       "Effect": "Allow",
>       "Action": [
>         "ec2:AllocateAddress",
>         "ec2:CancelSpotInstanceRequests",
>         "ec2:CreateTags",
>         "ec2:CreateVolume",
>         "ec2:Describe*",
>         "ec2:RequestSpotInstances",
>         "iam:CreateServiceLinkedRole",
>         "iam:GetInstanceProfile",
>         "iam:GetPolicy",
>         "iam:GetPolicyVersion",
>         "iam:GetRole",
>         "iam:GetRolePolicy",
>         "iam:ListPolicyVersions",
>         "iam:ListAttachedRolePolicies",
>         "iam:ListInstanceProfilesForRole",
>         "iam:PassRole"
>       ],
>       "Resource": [
>                 "*"
>       ]
>     },
>     {
>         "Sid": "MachineControllerManagerInstancesActions",
>         "Effect": "Allow",
>         "Action": [
>             "ec2:TerminateInstances",
>             "ec2:AttachVolume",
>             "ec2:DetachVolume",
>             "ec2:DeleteVolume"
>         ],
>         "Resource": [
>             "arn:aws:ec2:${var.region}:${var.aws_account_id}:instance/*",
>             "arn:aws:ec2:${var.region}:${var.aws_account_id}:volume/*",
>             "arn:aws:ec2:${var.region}:${var.aws_account_id}:security-group/*"
>         ],
>         "Condition": {
>             "StringEquals": {
>               "ec2:ResourceTag/${var.tag_key}": "${var.tag_value}"
>             }
>         }
>     },
>     {
>       "Sid": "MachineControllerManagerRunInstancesWithRequiredTag",
>       "Effect": "Allow",
>       "Action": [
>         "ec2:RunInstances"
>       ],
>       "Resource": [
>         "arn:aws:ec2:${var.region}:${var.aws_account_id}:instance/*"
>       ],
>       "Condition": {
>         "StringEquals": {
>           "aws:RequestTag/${var.tag_key}": "${var.tag_value}"
>         }
>       }
>     },
>     {
>       "Sid": "MachineControllerManagerRunInstancesActions",
>       "Effect": "Allow",
>       "Action": [
>         "ec2:RunInstances"
>       ],
>       "Resource": [
>         "arn:aws:ec2:${var.region}:${var.aws_account_id}:security-group/*",
>         "arn:aws:ec2:${var.region}:${var.aws_account_id}:subnet/*",
>         "arn:aws:ec2:${var.region}:${var.aws_account_id}:vpc/${var.vpc_id}",
>         "arn:aws:ec2:${var.region}:${var.aws_account_id}:network-interface/*",
>         "arn:aws:ec2:${var.region}:${var.aws_account_id}:key-pair/*",
>         "arn:aws:ec2:${var.region}:${var.aws_account_id}:volume/*",
>         "arn:aws:ec2:${var.region}::image/*"
>       ]
>     }
>   ]
> }
> EOF
> }
> ```
> 
> We should probably update the doc, to add IAM roles for each provider. cc: @hardikdr @prashanth26 @ggaurav10

thanks

**Comment by prashanth26** [comment]
Hi @zjj2wry,

I think @rewiko pretty much summed it up. Thanks for that. Apologies for the delay in response due to the vacation period.
