### ISSUE TITLE
no documentation about providers

### ISSUE THREAD

**Issue by lbvffvbl** [gardener/machine-controller-manager#588]
**What would you like to be added**: Hi, I'm using a machine-controller from kubermatic. Your controller interests me because you have metal-stack provider, but I did not found any information on how to use it. same about yandex, vmwarem kubevirt. I cant find machine classes for these providers. 

**Why is this needed**:  I can't try to use it because I don't know how to do it. It's a big problem with documentation

**Comment by hardikdr** [comment]
Hi @lbvffvbl, thanks for opening the issue.
At the moment, all the providers are being moved out of the tree, it'd mean, the provider-specific machine controller will be managed separately. 
Please follow the links below for the providers you mentioned:

* Metal-stack: https://github.com/metal-stack/machine-controller-manager-provider-metal
@gerrit can probably help there, with the sample machine-class, either in-tree or out-of-tree, whichever is being maintained at the moment. 

For the rest of them, 
* Vsphere:  Sample machine-class:  https://github.com/gardener/machine-controller-manager-provider-vsphere/blob/master/kubernetes/machine-class.yaml

* kubevirt: https://github.com/gardener/machine-controller-manager-provider-kubevirt/blob/master/kubernetes/machine-class.yaml .
I am not sure if it's really maintained, please open an issue there if needed to check.

* Yandex: https://github.com/flant/machine-controller-manager-provider-yandex
Sample machine-class is not maintained, I'll open an issue there. 

It probably also makes sense to have the pointers to these external repositories in the README of MCM.

**Comment by prashanth26** [comment]
I have updated the [Readme.md](https://github.com/gardener/machine-controller-manager/blob/master/README.md) to have links to all known OOT provider implementors for MCM.

/close
