### ISSUE TITLE
Orphaned AWS Route table block VPC deletion afterwards

### ISSUE THREAD

**Issue by wgabsi88** [gardener/machine-controller-manager#595]
**What happened**:
There was a leaked route table which prevent the deletion of the VPC
**What you expected to happen**:
The cluster deletion should delete all AWS resources in order to successfully delete the cluster
**How to reproduce it (as minimally and precisely as possible)**:
it occurs multiple times in our pipelines clusters and developer clusters deletion, but as sporadic issue
**Anything else we need to know**:
```
[2020-09-30T08:24:19.344Z] * Error deleting VPC: DependencyViolation: The vpc 'vpc-0d2464ee68f52acce' has dependencies and cannot be deleted.

[2020-09-30T08:24:19.344Z] 	status code: 400, request id: <omitted>
```
**Environment**:

**Comment by prashanth26** [comment]
HI @wgabsi88 ,

The `machine-controller-manager` component doesn't create any AWS routes (table entries). I think you meant to open this issue on another repo? Also can you please provide more details on the issue and any specific steps to reproduce this?

**Comment by dguendisch** [comment]
I guess the correct repo from gardener side would be https://github.com/gardener/terraformer.
We see this issue in gardener integration tests regularly as well but I think it's not really solvable here but only in upstream terraform.
I think @ialidzhikov already created a bunch of issues upstream.

**Comment by wgabsi88** [comment]
Hi @prashanth26, @dguendisch ,
apologies for choosing the wrong component, i will close the issue and look in terraformer repos for similar issues.

**Comment by dguendisch** [comment]
Maybe @ialidzhikov can point you to the resp. upstream issue(s).

**Comment by ialidzhikov** [comment]
The corresponding issues on upstream side:
- https://github.com/hashicorp/terraform-provider-aws/issues/12073
- https://github.com/hashicorp/terraform-provider-aws/issues/12829
