### ISSUE TITLE
Machines are restored very slowly during Control Plane Migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/machine-controller-manager#602]
**What happened**:
When we run [Control Plane Migration](https://github.com/gardener/gardener/blob/master/docs/proposals/07-shoot-control-plane-migration.md#leader-election-and-control-plane-termination), when the worker has to be restored on the __Destination Seed__ the following happens:
The `MachineDeployments`, `Machines`, `MachineSets` and `MachineClasses` are deployed while MCM is not running. Later, when MCM is started it should just resolve the owner references between the `Machines`, `MachineSets`, `MachineDeployments` and `MachineClasses` without recreating the nodes (the names of the nodes are already present in the respective labels of the machine resources).
The setting of these OwnerReferences can takes a lot of time - 6 minutes to more than 20 minutes which causes the MCM to flag the machines as Unhealthy and recreate them.
Previously the restoration took 1-2 minutes max.

**What you expected to happen**:
The owner references of the machine resources to be set faster so that the machines do not get recreated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `MachineDeployment` and wait for it to create the `MachineSets`, `Machines` and nodes in the cluster
2. Save all machine resources(deployment, sets, machine and class) locally
3. Stop MCM and delete the machine resources (deployment, sets, machine and class) by also removing their finalizers
4. Edit the resources you saved locally so that they do not contain OwnerReferences and any other values that point to other machine resources by UIDs. Remove any values from their `Status` fields apart from the one which holds the names of the created nodes
5. Recreate the machine resources, then update their status to include the name of the nodes
6. Start MCM and observe how much time it takes to mark the `Machines` as ready.

**Anything else we need to know**:

**Environment**
MCM v0.38

**Comment by prashanth26** [comment]
Fixed by https://github.com/gardener/gardener/pull/3970.
/close
