### ISSUE TITLE
Include Secrets in controlCoreObjects rather than targetCoreObjects

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/machine-controller-manager#616]
**What would you like to be added**:
In file [`machine_test.go`](https://github.com/gardener/machine-controller-manager/blob/ed6d2380902d9a15a82912e53e31ee609a9d4dc7/pkg/util/provider/machinecontroller/machine_test.go#L404) , secrets should be included in controlCoreObjects (which are presently in targetCoreObjects) and `controlCoreClient` should be used to `Get()` the secrets wherever applicable.
**Why is this needed**:
In MCM context, Secrets are core objects which we create in control cluster and not in target cluster, but in the file `machine_test.go` , all the `Describe` blocks have secrets being passed as targetCoreObject to create the fake controller using `createController()` method.

**Comment by AxiomSamarth** [comment]
Thank you, @himanshu-kun for raising this 👍🏻 That is a valid observation. Please raise a PR with the fix.

**Comment by prashanth26** [comment]
Nice catch.

@himanshu-kun - You mean [this right](https://github.com/gardener/machine-controller-manager/blob/ed6d2380902d9a15a82912e53e31ee609a9d4dc7/pkg/util/provider/machinecontroller/controller_suite_test.go#L488)?

**Comment by himanshu-kun** [comment]
Yes @prashanth26 
I was abt to discuss this in the meeting today
I think we need to setup a `coreControlSharedInformer` , which is not there currently.

**Comment by prashanth26** [comment]
Fixed by https://github.com/gardener/machine-controller-manager/pull/617. 
/close
