### ISSUE TITLE
Remove deprecated in-tree code

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#622]
**How to categorize this issue?**

/area dev-productivity
/kind cleanup
/priority 3

**What would you like to be added**:
Get rid of all deprecated in-tree machine controller code

- [x] Unused CRDS and API objects
- [x] Deprecated controller code
- [x] Unused metrics 

**Why is this needed**:
To get rid of os unused code. 
Depends on completion of https://github.com/gardener/machine-controller-manager/issues/211 to remove unused metrics and expose it elsewhere.

**Comment by AxiomSamarth** [comment]
@dkistner There is MCM In-Tree code which we would like to deprecate. As the MCM Out of Tree for all providers are available today. I want to understand the process followed in Gardener to deprecate any such dead/debt code?

**Comment by elankath** [comment]
Commencing this. <will update>

**Comment by himanshu-kun** [comment]
/close 
Done with #769
