### ISSUE TITLE
Improvements in IT Machine Controller Manager

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/machine-controller-manager#638]
**How to categorize this issue?**

/area testing
/kind enhancement
/priority 3

**What happened**:
Improvements in IT-suite required
**What you expected to happen**:
1. integration-test docs to run integration test locally should be modified to include new changes
2. v1 CRDs needs to be used 
3. MaxSurge of test-machineDeployments created should be increased to 2 as for Azure the test would timeout otherwise.
4. logic to know if string tags or key value pair tags are used , should be added.
5. machines created during tests should have different role tags as compared to usual machines created by MCM, so that orphan collection doesn't happen due to racing of MCM's in case when both control and target clusters are shoot clusters
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by prashanth26** [comment]
Hi @himanshu-kun ,

I think the error is right. However, I think the `clusterName` variable is used in several other places for targetting the control cluster. Should it then make sense to have two variables `controlClusterName` and a `targetClusterName` for different use cases and use the `targetClusterName` for [this call](https://github.com/gardener/machine-controller-manager/blob/master/pkg/test/integration/common/framework.go#L719)?

Also in the future, it would help if you can link the lines with the issues to make looking up code faster.

**Comment by himanshu-kun** [comment]
yeah sorry for that @prashanth26  I would link up the lines surely from next time

**Comment by prashanth26** [comment]
Sorry, i didn't look through the code. So i think you mean that [this vairbale] https://github.com/gardener/machine-controller-manager/blob/master/pkg/test/integration/common/framework.go#L701 should've been `target` inside of control right?

**Comment by himanshu-kun** [comment]
> Sorry, i didn't look through the code. So i think you mean that [this variable](https://github.com/gardener/machine-controller-manager/blob/master/pkg/test/integration/common/framework.go#L701) should've been `target` inside of control right?

yes I wanted [this](https://github.com/gardener/machine-controller-manager/blob/6b9d5b4f6a87054aac63137b16ff3e36fdf946e4/pkg/test/integration/common/framework.go#L701) line to be `clusterName, err := c.TargetCluster.ClusterName()`

**Comment by prashanth26** [comment]
> > Sorry, i didn't look through the code. So i think you mean that [this variable](https://github.com/gardener/machine-controller-manager/blob/master/pkg/test/integration/common/framework.go#L701) should've been `target` inside of control right?
> 
> yes I wanted [this](https://github.com/gardener/machine-controller-manager/blob/6b9d5b4f6a87054aac63137b16ff3e36fdf946e4/pkg/test/integration/common/framework.go#L701) line to be `clusterName, err := c.TargetCluster.ClusterName()`

Sure I think you can make this change and raise a PR on master. We can cherry-pick and make a release 0.40.1 with this. However, just cross-check with Jakeer's AWS PR to see if this change is as desired and shouldn't affect the AWS PR.

**Comment by AxiomSamarth** [comment]
More improvements/refactoring 

- Introduce better AND logic here
- Remove the check of MC & MCM image as the validation has been done before the method call
- Make the Image name prefix a global variable

Changes are done via [this](https://github.com/himanshu-kun/machine-controller-manager/pull/1) PR

**Comment by AxiomSamarth** [comment]
This is the function in MCM IT Suite ([link](https://github.com/gardener/machine-controller-manager/blob/6b9d5b4f6a87054aac63137b16ff3e36fdf946e4/pkg/test/integration/common/helpers/cluster.go#L67-L85))

```
// IsSeed checks whether the cluster is seed of target cluster
func (c *Cluster) IsSeed(target *Cluster) bool {
	targetClusterName, _ := target.ClusterName()
	nameSpaces, _ := c.Clientset.CoreV1().Namespaces().List(context.Background(), metav1.ListOptions{})
	for _, namespace := range nameSpaces.Items {
		if namespace.Name == targetClusterName {
			return true
		}
	}
	return false
}
```

Scenario - 
 - If this test is subject to a `shoot` which is acting as both `control` & `target` cluster and if the `shoot` (hypothetically) has a namespace `shoot--<project-name>--<shoot-name>` then this function will treat control cluster to be a seed cluster.
- Thus not deploying CRDs, not deploying MCM, not deploying MachineClass from file, not creating secrets and the whole flow may fail.

cc: @prashanth26 @himanshu-kun @rkjakeer

**Comment by himanshu-kun** [comment]
> This is the function in MCM IT Suite ([link](https://github.com/gardener/machine-controller-manager/blob/6b9d5b4f6a87054aac63137b16ff3e36fdf946e4/pkg/test/integration/common/helpers/cluster.go#L67-L85))
> 
> ```
> // IsSeed checks whether the cluster is seed of target cluster
> func (c *Cluster) IsSeed(target *Cluster) bool {
> 	targetClusterName, _ := target.ClusterName()
> 	nameSpaces, _ := c.Clientset.CoreV1().Namespaces().List(context.Background(), metav1.ListOptions{})
> 	for _, namespace := range nameSpaces.Items {
> 		if namespace.Name == targetClusterName {
> 			return true
> 		}
> 	}
> 	return false
> }
> ```
> 
> Scenario -
> 
> * If this test is subject to a `shoot` which is acting as both `control` & `target` cluster and if the `shoot` (hypothetically) has a namespace `shoot--<project-name>--<shoot-name>` then this function will treat control cluster to be a seed cluster whereas in reality is it not a seed cluster.
> * Thus, the suite will not deploy CRDs, will not deploy MCM, will not deploy MachineClass from file, will not create secrets and the whole flow may fail.
> 
> cc: @prashanth26 @himanshu-kun @rkjakeer

Yes nice catch @AxiomSamarth , we can add an `if` condition here for the same

**Comment by AxiomSamarth** [comment]
Here in [this](https://github.com/himanshu-kun/machine-controller-manager/blob/e14d453347bd3dc5d9c2b17b0e2d86449283a9f8/pkg/test/integration/common/framework.go#L641-L651) code section, an MCM deployment is created in the control cluster because the control cluster is not a seed. Which means, probably it is a `Shoot` which will have its own MCM deployment in the `Shoot namespace` of its `Seed`. 

The original MCM deployed in the actual seed must be scaled down to 0. otherwise, the machines created by integration tests may be orphan collected.

**Comment by himanshu-kun** [comment]
> Here in [this](https://github.com/himanshu-kun/machine-controller-manager/blob/e14d453347bd3dc5d9c2b17b0e2d86449283a9f8/pkg/test/integration/common/framework.go#L641-L651) code section, an MCM deployment is created in the control cluster because the control cluster is not a seed. Which means, probably it is a `Shoot` which will have its own MCM deployment in the `Shoot namespace` of its `Seed`.
> 
> The original MCM deployed in the actual seed must be scaled down to 0. otherwise, the machines created by integration tests may be orphan collected. However, I am not able to think of a way to scale it down because there is no reference to the actual Seed anywhere.

Yes @AxiomSamarth you are right.. if thats the case even [here](https://github.com/himanshu-kun/machine-controller-manager/blob/e14d453347bd3dc5d9c2b17b0e2d86449283a9f8/pkg/test/integration/common/framework.go#L655-L658) we don't need the `if` condition to check that control cluster is seed of target cluster , because we need to scaleDown the machineDeployment in seed of target cluster in all the cases as we are running mc and mcm locally in this case.

**Comment by AxiomSamarth** [comment]
1. There should be a check [here](https://github.com/gardener/machine-controller-manager/blob/6b9d5b4f6a87054aac63137b16ff3e36fdf946e4/pkg/test/integration/common/framework.go#L470-L475) to validate if path of MachineClass v1 is supplied or not for more graceful execution.

2. Today, if the control cluster is a seed cluster then the MachineClass from the target namespace is reemployed & patched with IT tags. This is fair enough. However, I think there should also be a scope to supply a custom MachineClass & execute the tests. So, @himanshu-kun when you are making the change, can you modify the logic of [setupMachineClass](https://github.com/gardener/machine-controller-manager/blob/6b9d5b4f6a87054aac63137b16ff3e36fdf946e4/pkg/test/integration/common/framework.go#L459) to use the existing machineClass if MachineClass is not explicitly passed.
