### ISSUE TITLE
AWS: Missing `iops` when using `io1 volume type

### ISSUE THREAD

**Issue by rfranzke** [gardener/machine-controller-manager#69]
When creating a machine with volume type `io1` the MCM does not specify the `iops` parameter, resulting in the following error:
`I0420 06:21:27.447052       1 machine.go:301] Error while creating machine <machineName>: InvalidParameterCombination: The parameter iops must be specified for io1 volumes.`

**Comment by prashanth26** [comment]
[This PR](Handling IOPs when creating volume of type AWS io1) closes this issue

**Comment by vlerenc** [comment]
I believe, `io1` wasn't reenabled as it is still missing in cloud profile and dashboard, right? Change https://github.wdf.sap.corp/kubernetes/landscape-setup/commit/3bb8c9295732d784265218e2fb1033c8a0365454#diff-7f6d64702b8513c2de9ab0737dbbd00f needs to be reverted to get io1 back again.

cc @rfranzke @freegroup

**Comment by rfranzke** [comment]
We do not expose `iops` field to the Shoot manifest. We cannot simply revert it but need adaption in Gardener and Shoot API spec to support `io1` volumes.

**Comment by vlerenc** [comment]
Then we should reopen this ticket, I guess.

**Comment by PadmaB** [comment]
Necessary changes has been made in MCM, changes are required from Gardener and Dashboard.
**Ref:** https://github.com/gardener/gardener/issues/726 and https://github.com/gardener/dashboard/issues/306
