### ISSUE TITLE
Controller got hung and didn't reconcile machine object

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#71]
While performing a rolling update, the old machine object was not deleted and the controller only responded once it was restarted. Will have to look into this issue. 

Was it because safety controller as processing the object? Or is it a more generic problem as it was seen in gardener as well. Not sure. Need to dig in more.

**Comment by hardikdr** [comment]
This should be resolved as following PRs were merged.
- https://github.com/gardener/machine-controller-manager/pull/117/commits/0f01449e27e16394c6a74408eca93e6e292abc34
- https://github.com/gardener/machine-controller-manager/pull/116

Please re-open if see the same issue again.
