### ISSUE TITLE
Exponential backoff for unfreeze

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#75]
Currently the machine-controller-manager has a permanent freeze logic when the machines are not able to join the cluster in a configurable time. This however is counter productive when the provider/network is down, as in this case the cluster is permanently down.

Solution: Have an exponential backoff

**Comment by vlerenc** [comment]
From our sync:
> Setting the Scene/Freeze happens when:
> * Actual vs. desired number of nodes goes beyond a certain threshold, which freezes the machine set (first) and deployment (freeze means the MCM stops acting on that set/deployment; delete continues to work and when actual vs. desired goes below the threshold, the set/deployment is unfrozen)
> * Machine doesn’t come up a configurable time (no unfreeze logic implemented yet)

Let’s go for exponential back-off, which seems to be the cleanest approach (timeout cap can be configured).

**Comment by rfranzke** [comment]
BTW: When an objects `deletionTimestamp` is set we should automatically unfreeze.

**Comment by prashanth26** [comment]
We have disabled the permanent freeze for now in our MCM. We will hold on from implementing the exponential backoff for unfreeze until we come up with a need for the same.

**Comment by prashanth26** [comment]
Related to https://github.com/gardener/machine-controller-manager/issues/155 hence closing this issue and tracking it in a single one.
