### ISSUE TITLE
Update Go Version on MCM & providers to v1.19

### ISSUE THREAD

**Issue by rishabh-11** [gardener/machine-controller-manager#752]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 3

**What would you like to be added**:
Update the go version to 1.19

- [x] Machine Controller Manager(@rishabh-11)
https://github.com/gardener/machine-controller-manager/pull/753
- [x] Machine Controller Manager Provider AWS (@rishabh-11)
https://github.com/gardener/machine-controller-manager-provider-aws/pull/98
- [x] Machine Controller Manager Provider Azure (@rishabh-11)
https://github.com/gardener/machine-controller-manager-provider-azure/pull/75
- [x] Machine Controller Manager Provider Alicloud (@rishabh-11)
https://github.com/gardener/machine-controller-manager-provider-alicloud/pull/37
- [x] Machine Controller Manager Provider GCP (@rishabh-11)
https://github.com/gardener/machine-controller-manager-provider-gcp/pull/56
- [x] Machine Controller Manager Provider OpenStack
https://github.com/gardener/machine-controller-manager-provider-openstack/pull/73
- [x] Machine Controller Manager Provider vSphere (cc @briantopping)
https://github.com/gardener/machine-controller-manager-provider-vsphere/pull/43

**Why is this needed**:

**Comment by briantopping** [comment]
Note that the [v0.17.0 MCM vSphere](https://github.com/gardener/machine-controller-manager-provider-vsphere/releases/tag/v0.17.0) is based on `1.19.2`. The `go.mod` still shows 1.18, but that's the language level, not the build foundation and library level.

**Comment by rishabh-11** [comment]
> Note that the [v0.17.0 MCM vSphere](https://github.com/gardener/machine-controller-manager-provider-vsphere/releases/tag/v0.17.0) is based on `1.19.2`. The `go.mod` still shows 1.18, but that's the language level, not the build foundation and library level.

I had a beginner's doubt. If the `go.mod` is using `1.18`, when I run `go mod tidy` and `go mod vendor`, wouldn't it cause the dependencies to be based on `go 1.18` and not `1.19`?

**Comment by briantopping** [comment]
My interpretation of the [go directive](https://go.dev/ref/mod#go-mod-file-go) is it was originally designed for minimum semantic expectations of the language and build system. As that document suggests, the language has not yet had a semantic incompatibility and the changes it ends up pertaining to are for build tooling.

In other words, the go directive should map to the semantics of the project sources and the binary results of the build are based on input artifacts such as the base image provided to Docker. So long as the language and build tool improvements are forward compatible, it doesn't hurt to upgrade the go directive and increase the expectations, but it doesn't provide any value or change either.

To put a finer point on it, increasing the go directive to 1.17 or later requires that the dependencies have explicit versions on them. Once that happens, each dependency version must be upgraded, usually via `go mod tidy`. Note that will upgrade the dependencies, but not the base image and standard go library.
