### ISSUE TITLE
Force Drain and detachment for Volumes for Unhealthy Nodes which were `NotReady` for over 5min

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/machine-controller-manager#781]
**How to categorize this issue?**

/area performance
/kind bug
/priority 2

**What happened**:

Currently we skip drain for an unhealthy node which we want to remove, if we see that it was not Ready for >5 min.
We have now seen problems with this. Imagine a node with a lot of PVs attached. Now node goes unhealthy and we skip drain, and start deleting the VM. 
In azure as part of deletion we currently detach the volumes from the VM (PV disks and root disk) and then proceed with VM deletion.
This means MCM now will detach the backing disks of the PVs for the pods directly and then trigger node deletion. K8s starts acting only after node deletion as till now everything was happening on infra.
KCM deletes the nodes, and then the orphan pod force deletion logic removes the pods. This only makes the attach/detach controller come into action.
The attach/detach controller relies on kubelet to direct CSI driver on the node to unmount the disk. Since there is no node , meaning no kubelet , the A/D controller waits till `maxWaitForUnmountDuration` (6min , non-configurable) and then only force detachment starts.

So there are two detachments , one by MCM and then by A/D controller. This leads to downtimes for the customers.

**What you expected to happen**:

Expect the pods with PV to recover faster after unhealthy nodes are removed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

During normal draining a wait for detachment and wait for reattachment( wait for new volumeattachment formation in case volumeattachment support is enabled) is done , introduced in https://github.com/gardener/machine-controller-manager/pull/608

live issue # 3645

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by himanshu-kun** [comment]
Proposed solutions:

* Raise issue on upstream so that unmounting attempt is not made if kubelet status is unknown or node is deleted.
* MCM should force delete the pods, and then wait until the `node.status.volumeAttached` becomes empty. After that only proceed with VM deletion.
* Delete the node object before deleting the VM. This way KCM's garbage collection would delete the pods and A/D controller would start detachment. But we need to figure out a way(like using volumeAttachments) to make sure not to start VM deletion before detachment is complete.

cc @dguendisch

**Comment by himanshu-kun** [comment]
## Proposals after grooming

We have decided to do some testing , where we would first delete the node object and then delete the VM or delete them both in parallel. This would mean A/D controller detaching volumes and MCM azure(for now) also doing the detachment.
This decision was taken after going through the recommended approach of deleting pods https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/#delete-pods where its stated that deleting nodes is favoured over force deleting pods especially for pods with PV.

**Comment by vlerenc** [comment]
From https://github.tools.sap/kubernetes-live/issues-live/issues/2556 mentioned by @himanshu-kun:

> This make the KCM wait for the unmounting of volume. Unmounting is done by csi plugin on direction of kubelet of the node. But since node is gone => no kubelet and unmounting never happens
Why does KCM wait for the unmounting of volumes if the node is gone. Does that make sense? And how does it know that (where is the mount information persisted) and how does it do it? 

The reconciler https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L232 works on https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/cache/actual_state_of_world.go#L156 that is set by https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/cache/actual_state_of_world.go#L388 which is called here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go#L667, but that only works with a node resource. To me this sounds somewhat strange, if it really depends on the node that is gone, is it not? Is it keeping that state in memory, because otherwise it wouldn’t know anymore, if the source of truth is the (missing) node resource and it got restarted.

**Comment by elankath** [comment]
Hi Vedran, 

We discussed this and we agree that it is best to the following enhancements:
1. Initiate our drain routine (with forceful pod deletion) if the Node does not have the `Ready` condition for 5 min or has the `ReadOnlyFileSystem` is true for 5min. We also delete the [VolumeAttachments](https://pkg.go.dev/k8s.io/api/storage/v1#VolumeAttachment) associated with the node.
     1. The k8s attach-detach controller will come into play. However, it will still wait for `maxUnmountDuration` `6min` before force detaching.
1. Before Initiating VM Deletion, we wait for the node volumes to be detached by checking `node.Status.volumesAttached` (till a timeout)
1. Once volumes are detached, we proceed with the VM Deletion as usual. This involves the call to [Driver.DeleteMachine](https://github.com/gardener/machine-controller-manager/blob/v0.48.2/pkg/util/provider/machinecontroller/machine_util.go#L1152).
1. We then delete the node as usual.


### Detailed Proposal 
(this section is only of relevance to implementors)
TODO

**Comment by elankath** [comment]
live # 3645
