### ISSUE TITLE
SSD volumes on GCP not working

### ISSUE THREAD

**Issue by rfranzke** [gardener/machine-controller-manager#83]
When trying to create a machine with a GCP class referencing a `pd-ssd` disk, MCM fails to create it:

`I0515 09:03:02.332653       1 machine_util.go:157] Validation of GCPMachineClass failed spec.disks[0].type: Unsupported value: "pd-ssd": supported values: "pd-standard", "pd-ssd"`

**Comment by hardikdr** [comment]
Thanks for reporting, looking into it.
