### ISSUE TITLE
Only MachineDeployment unfrozen on reconciliation. MachineSet remains frozen.

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/machine-controller-manager#88]
Pre-condition: MachineDeployment for a shoot cluster was created by Gardener and both the MachineDeployment and its MachineSet are frozen due to some issue.

Action: Edit the shoot yaml to change the min and max values to a smaller value than the current replica value of MachineDeployment.

Observed Behaviour: MachineDeployment is reconciled to the new replica value and the freeze label is removed. But the MachineSet remains in frozen state until the label is manually removed.

Expected Behaviour: Both the MachineDeployment are unfrozen after reconciliation.

**Comment by amshuman-kr** [comment]
@hardikdr It might be ok for Gardener to choose to ignore the freeze label during regular reconciliation.

But if the shoot yaml is edited (which is the scenario I reported) then Gardener should update the machinedeployment and in turn remove the freeze label, don't you think?

**Comment by hardikdr** [comment]
I think Gardener should patch the existing MachineDeployment with new value rather than completely updating it.
I would prefer to give the responsibility of removing Freeze label only to Safety-controller and no one else.
What do you think?

**Comment by amshuman-kr** [comment]
Fair enough. But then safety controller might have to be more intelligent than it is right now. Perhaps exponential backoff can be part of that additional intelligence.

**Comment by hardikdr** [comment]
Yes, that's correct.

**Comment by prashanth26** [comment]
closing issue as I don't think this occurs anymore. Please reopen if reproducible.
