### ISSUE TITLE
Api reference links are broken

### ISSUE THREAD

**Issue by Kostov6** [gardener/machine-controller-manager#918]
**How to categorize this issue?**

/area documentation
/kind bug
/priority 3

**What happened**:
There are a lot of broken links like [MachineSpec](https://github.com/gardener/machine-controller-manager/blob/master/docs/documents/apis.md#%23machine.sapcloud.io%2fv1alpha1.MachineSpec)

**What you expected to happen**:
It should work like https://github.com/gardener/etcd-druid-api/blob/main/docs/api-reference/druid.md

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by elankath** [comment]
all generated internal links are having double '#''s in them.

**Comment by elankath** [comment]
We have identified this as a long-standing bug after the CRD binary was updated and `linkForType` invocation in Go template wasn't changed. We are fixing this. Thanks for catching this.
