### ISSUE TITLE
vSphere support in Gardener/MCM

### ISSUE THREAD

**Issue by fdhex** [gardener/machine-controller-manager#93]
As vSphere is currently not one of the supported Cloud Providers, I was wondering if there was already some initial work on the topic or if this is still a greenfield for Gardener? Is there any interest in such a feature?

**Comment by prashanth26** [comment]
Currently there has been no work carried out to support vSphere to the best of my knowledge. @hardikdr could probably comment more on this. However, there is an active interest in support for vSphere. Our plan is to support vSphere some where down the line. 

However if you/anyone else are interested in contributing for the initial support for vSphere, we are more than happy to help you with guiding you towards the steps to do the same. 

Thanks & Regards,
Prashanth

**Comment by hardikdr** [comment]
Yes, we would be really happy to have vSphere support.

Btw, we have documented simple steps to add support for new cloud provider here: https://github.com/gardener/machine-controller-manager/blob/master/docs/development/new_cp_support.md
- Check AWS implementation for reference.
  - https://github.com/gardener/machine-controller-manager/blob/master/pkg/driver/driver_aws.go

**Comment by vasu1124** [comment]
cf. https://github.com/kubernetes/community/tree/master/sig-vmware, we will likely discuss with the SIG VMware the same subject next week, please join.

**Comment by vlerenc** [comment]
+1

**Comment by vpnachev** [comment]
Now we have https://github.com/gardener/machine-controller-manager-provider-vsphere, so this issue can be closed? 

Based on https://github.com/gardener/gardener-extension-provider-vsphere/blob/59e3c58dfb9f0fdd5fe315b84659bf07e056bbed/charts/images.yaml#L29-L34 is there something from https://github.com/MartinWeindel/machine-controller-manager/ that prevents the closing of the issue?
cc @MartinWeindel @marwinski

**Comment by MartinWeindel** [comment]
The vSphere provider relies on the out-of-tree machine-controller manager which is not yet released.
Besides we are still evaluating if we could already use the new "Simplified API" of NSX-T instead of the old "Advanced API".
So at the moment we have some kind of alpha version of vSphere support but some work is left to stabilise it.

**Comment by vpnachev** [comment]
Ok, so once the out-of-tree support MCM is released, this issue can be closed as resolved.

Regarding switch between `Simplified` and `Advanced` API of NXS-T, it should not affect the MCM and can be tracked in https://github.com/gardener/gardener-extension-provider-vsphere or https://github.com/gardener/machine-controller-manager-provider-vsphere.

**Comment by prashanth26** [comment]
This is completed here - https://github.com/gardener/machine-controller-manager-provider-vsphere. Thanks to @MartinWeindel.
