### ISSUE TITLE
Introduce gosec for Static Application Security Testing (SAST)

### ISSUE THREAD

**Issue by rishabh-11** [gardener/machine-controller-manager#948]
**How to categorize this issue?**

/area compliance
/area security
/kind enhancement
/priority 1

**What would you like to be added**:
use `gosec` for SAST. Check https://github.com/gardener/gardener/pull/9959 for reference.

- [x] mcm - https://github.com/gardener/machine-controller-manager/pull/954
- [x] mcm-provider-aws - https://github.com/gardener/machine-controller-manager-provider-aws/pull/179
- [x] mcm-provider-azure - https://github.com/gardener/machine-controller-manager-provider-azure/pull/169
- [x] mcm-provider-gcp - https://github.com/gardener/machine-controller-manager-provider-gcp/pull/134
- [x] mcm-provider-openstack - https://github.com/gardener/machine-controller-manager-provider-openstack/pull/199

**Why is this needed**:
Please look at the mail from Claudia with the title `Enable security linting in your repository by end of 2024` for details.

**Comment by aaronfern** [comment]
Closing as all PRs are merged
/close
